<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emi Cervantes">
<meta name="dcterms.date" content="2023-07-28">

<title>Modeling Final Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="modeling-final_files/libs/clipboard/clipboard.min.js"></script>
<script src="modeling-final_files/libs/quarto-html/quarto.js"></script>
<script src="modeling-final_files/libs/quarto-html/popper.min.js"></script>
<script src="modeling-final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="modeling-final_files/libs/quarto-html/anchor.min.js"></script>
<link href="modeling-final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="modeling-final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="modeling-final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="modeling-final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="modeling-final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link active" data-scroll-target="#load-libraries"><span class="header-section-number">1</span> Load Libraries</a></li>
  <li><a href="#load-dataset" id="toc-load-dataset" class="nav-link" data-scroll-target="#load-dataset"><span class="header-section-number">2</span> Load Dataset</a>
  <ul class="collapse">
  <li><a href="#clean-dataset" id="toc-clean-dataset" class="nav-link" data-scroll-target="#clean-dataset"><span class="header-section-number">2.1</span> Clean Dataset</a></li>
  </ul></li>
  <li><a href="#checking-pretest-score-difference" id="toc-checking-pretest-score-difference" class="nav-link" data-scroll-target="#checking-pretest-score-difference"><span class="header-section-number">3</span> Checking Pretest Score Difference</a>
  <ul class="collapse">
  <li><a href="#split-data-into-chicago-and-irvine" id="toc-split-data-into-chicago-and-irvine" class="nav-link" data-scroll-target="#split-data-into-chicago-and-irvine"><span class="header-section-number">3.1</span> Split data into Chicago and Irvine</a></li>
  </ul></li>
  <li><a href="#checking-gender-difference-in-math-anxiety" id="toc-checking-gender-difference-in-math-anxiety" class="nav-link" data-scroll-target="#checking-gender-difference-in-math-anxiety"><span class="header-section-number">4</span> Checking Gender Difference in Math Anxiety</a>
  <ul class="collapse">
  <li><a href="#chicago-data" id="toc-chicago-data" class="nav-link" data-scroll-target="#chicago-data"><span class="header-section-number">4.1</span> Chicago Data</a></li>
  <li><a href="#irvine-data" id="toc-irvine-data" class="nav-link" data-scroll-target="#irvine-data"><span class="header-section-number">4.2</span> Irvine Data</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">5</span> Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#posttest-accuracy-scores" id="toc-posttest-accuracy-scores" class="nav-link" data-scroll-target="#posttest-accuracy-scores"><span class="header-section-number">5.1</span> Posttest Accuracy Scores</a>
  <ul class="collapse">
  <li><a href="#chicago-data-1" id="toc-chicago-data-1" class="nav-link" data-scroll-target="#chicago-data-1"><span class="header-section-number">5.1.1</span> Chicago Data</a></li>
  <li><a href="#irvine-data-1" id="toc-irvine-data-1" class="nav-link" data-scroll-target="#irvine-data-1"><span class="header-section-number">5.1.2</span> Irvine Data</a></li>
  </ul></li>
  <li><a href="#perceived-understanding" id="toc-perceived-understanding" class="nav-link" data-scroll-target="#perceived-understanding"><span class="header-section-number">5.2</span> Perceived Understanding</a>
  <ul class="collapse">
  <li><a href="#chicago-data-2" id="toc-chicago-data-2" class="nav-link" data-scroll-target="#chicago-data-2"><span class="header-section-number">5.2.1</span> Chicago Data</a></li>
  <li><a href="#irvine-data-2" id="toc-irvine-data-2" class="nav-link" data-scroll-target="#irvine-data-2"><span class="header-section-number">5.2.2</span> Irvine Data</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5.3</span> Results</a></li>
  </ul></li>
  <li><a href="#path-analysis" id="toc-path-analysis" class="nav-link" data-scroll-target="#path-analysis"><span class="header-section-number">6</span> Path Analysis</a>
  <ul class="collapse">
  <li><a href="#posttest-acucracy-scores" id="toc-posttest-acucracy-scores" class="nav-link" data-scroll-target="#posttest-acucracy-scores"><span class="header-section-number">6.1</span> Posttest Acucracy Scores</a>
  <ul class="collapse">
  <li><a href="#chicago-data-3" id="toc-chicago-data-3" class="nav-link" data-scroll-target="#chicago-data-3"><span class="header-section-number">6.1.1</span> Chicago Data</a></li>
  <li><a href="#irvine-data-3" id="toc-irvine-data-3" class="nav-link" data-scroll-target="#irvine-data-3"><span class="header-section-number">6.1.2</span> Irvine Data</a></li>
  <li><a href="#visualize-results" id="toc-visualize-results" class="nav-link" data-scroll-target="#visualize-results"><span class="header-section-number">6.1.3</span> Visualize Results</a></li>
  </ul></li>
  <li><a href="#perceived-understanding-1" id="toc-perceived-understanding-1" class="nav-link" data-scroll-target="#perceived-understanding-1"><span class="header-section-number">6.2</span> Perceived Understanding</a>
  <ul class="collapse">
  <li><a href="#chicago-data-4" id="toc-chicago-data-4" class="nav-link" data-scroll-target="#chicago-data-4"><span class="header-section-number">6.2.1</span> Chicago Data</a></li>
  <li><a href="#irvine-data-4" id="toc-irvine-data-4" class="nav-link" data-scroll-target="#irvine-data-4"><span class="header-section-number">6.2.2</span> Irvine Data</a></li>
  <li><a href="#visualize-results-1" id="toc-visualize-results-1" class="nav-link" data-scroll-target="#visualize-results-1"><span class="header-section-number">6.2.3</span> Visualize Results</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="modeling-final.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="modeling-final.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modeling Final Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emi Cervantes </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 28, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="load-libraries" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Load Libraries</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-15
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semptools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-dataset" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Load Dataset</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(<span class="st">'../../../data/math-anxiety-raw-data.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `Subject ID #` -&gt; `Subject ID #...8`
• `Subject ID #` -&gt; `Subject ID #...9`
• `StartDate` -&gt; `StartDate...11`
• `EndDate` -&gt; `EndDate...12`
• `Progress` -&gt; `Progress...13`
• `Duration (in seconds)` -&gt; `Duration (in seconds)...17`
• `Finished` -&gt; `Finished...18`
• `RecordedDate` -&gt; `RecordedDate...19`
• `Browser_info_Browser` -&gt; `Browser_info_Browser...20`
• `Browser_info_Version` -&gt; `Browser_info_Version...21`
• `Browser_info_Operating System` -&gt; `Browser_info_Operating System...22`
• `Browser_info_Resolution` -&gt; `Browser_info_Resolution...23`
• `Misc_0` -&gt; `Misc_0...36`
• `Misc_1` -&gt; `Misc_1...100`
• `Misc_2` -&gt; `Misc_2...145`
• `MW_control_1` -&gt; `MW_control_1...210`
• `MW_control_2` -&gt; `MW_control_2...211`
• `MW_control_3` -&gt; `MW_control_3...212`
• `MW_control_4` -&gt; `MW_control_4...213`
• `MW_control_5` -&gt; `MW_control_5...214`
• `` -&gt; `...219`
• `StartDate` -&gt; `StartDate...221`
• `EndDate` -&gt; `EndDate...222`
• `Progress` -&gt; `Progress...223`
• `Duration (in seconds)` -&gt; `Duration (in seconds)...224`
• `Finished` -&gt; `Finished...225`
• `RecordedDate` -&gt; `RecordedDate...226`
• `Browser_info_Browser` -&gt; `Browser_info_Browser...227`
• `Browser_info_Version` -&gt; `Browser_info_Version...228`
• `Browser_info_Operating System` -&gt; `Browser_info_Operating System...229`
• `Browser_info_Resolution` -&gt; `Browser_info_Resolution...230`
• `Misc_0` -&gt; `Misc_0...232`
• `Misc_1` -&gt; `Misc_1...239`
• `Misc_2` -&gt; `Misc_2...290`
• `MW_control_1` -&gt; `MW_control_1...295`
• `MW_control_2` -&gt; `MW_control_2...296`
• `MW_control_3` -&gt; `MW_control_3...297`
• `MW_control_4` -&gt; `MW_control_4...298`
• `MW_control_5` -&gt; `MW_control_5...299`</code></pre>
</div>
</div>
<section id="clean-dataset" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="clean-dataset"><span class="header-section-number">2.1</span> Clean Dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tma_lst <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"TMA_1"</span>, <span class="st">"TMA_2"</span>, <span class="st">"TMA_3"</span>,<span class="st">"TMA_4"</span>, <span class="st">"TMA_5"</span>, <span class="st">"TMA_6"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>             <span class="st">"TMA_sum"</span>, <span class="st">"TMA_avg"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(Condition, Sex, chicago, nonwhite, pretest,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>              MW_day1_avg, MW_day2_avg, SI_avg, tma_lst,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>              Understand_avg, Del_OverallAcc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %&gt;% select(tma_lst)

  # Now:
  data %&gt;% select(all_of(tma_lst))

See &lt;https://tidyselect.r-lib.org/reference/faq-external-vector.html&gt;.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get rid of row that has NA values in Condition and/or Sex</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> Condition <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sex))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>Condition[df1<span class="sc">$</span>Condition <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign 0 for "boy" and 1 for "girl"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>Sex[df1<span class="sc">$</span>Sex <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>Sex[df1<span class="sc">$</span>Sex <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure variable is categorical</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>chicago <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df1<span class="sc">$</span>chicago)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>Sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df1<span class="sc">$</span>Sex)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>nonwhite <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df1<span class="sc">$</span>nonwhite)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>df1<span class="sc">$</span>Condition <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df1<span class="sc">$</span>Condition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="checking-pretest-score-difference" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Checking Pretest Score Difference</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">pre_avg =</span> <span class="fu">mean</span>(pretest, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> chicago, <span class="at">y =</span> pre_avg))<span class="sc">+</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"#ef476f"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(pre_avg,<span class="dv">2</span>)),  <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Location"</span>, <span class="at">y =</span> <span class="st">"Pretest Score"</span>) <span class="sc">+</span> </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Irvine"</span>, <span class="st">"Chicago"</span>)) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the previous analysis, we saw that more student in Irvine already knew how to use ratio tactics before the study than students in Chicago. We want to check if the pretest score difference is significant across the sites by using student’s t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pretest <span class="sc">~</span> chicago, <span class="at">data =</span> df1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  pretest by chicago
t = 2.2026, df = 76.3, p-value = 0.03064
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.01665668 0.33096711
sample estimates:
mean in group 0 mean in group 1 
      0.6836158       0.5098039 </code></pre>
</div>
</div>
<p>The result shows that the difference is significant (p-value = 0.03). Since both sites are significantly different, we will treat each site as separate data.</p>
<section id="split-data-into-chicago-and-irvine" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="split-data-into-chicago-and-irvine"><span class="header-section-number">3.1</span> Split data into Chicago and Irvine</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># chicago data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df_i <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># irvine data</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>df_c <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="checking-gender-difference-in-math-anxiety" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Checking Gender Difference in Math Anxiety</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># labels </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>cond <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"No Worked EX"</span>, <span class="st">"Worked EX"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cond) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>location <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Irvine"</span>, <span class="st">"Chicago"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(location) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># TMA mean by site, condition, and gender</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago, Condition, Sex) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(TMA_avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'chicago', 'Condition'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># math anxiety density plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TMA_avg, <span class="at">fill =</span> Sex,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> Sex)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data=</span>mu, <span class="fu">aes</span>(<span class="at">xintercept=</span>mean, <span class="at">color=</span>Sex),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Condition),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">cols =</span> <span class="fu">vars</span>(chicago),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Math Anxiety"</span>, <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Gender"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) <span class="sc">+</span><span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We see from the figure that in Irvine schools, girls seemed to have a higher average math anxiety than boys in both condition. However, in Chicago schools, boys seemed to have a higher math anxiety than girls in both condition.</p>
<p>Girls seemed to have a higher math anxiety compared to boys overall. Check if the difference is significant in each site by using ANOVA test:</p>
<section id="chicago-data" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="chicago-data"><span class="header-section-number">4.1</span> Chicago Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>m1_c <span class="ot">&lt;-</span> <span class="fu">aov</span>(TMA_avg <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> Condition<span class="sc">*</span>Sex, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df_c)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value Pr(&gt;F)
Condition       1   0.80  0.7978   1.288  0.258
Sex             1   0.61  0.6106   0.986  0.322
Condition:Sex   1   0.00  0.0024   0.004  0.950
Residuals     174 107.79  0.6195               </code></pre>
</div>
</div>
<p>No significant difference between gender on learning achievement and math anxiety was found by gender.</p>
</section>
<section id="irvine-data" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="irvine-data"><span class="header-section-number">4.2</span> Irvine Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m1_i <span class="ot">&lt;-</span> <span class="fu">aov</span>(TMA_avg <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> Condition<span class="sc">*</span>Sex, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df_i)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)
Condition      1   0.02  0.0160   0.022  0.882
Sex            1   0.59  0.5868   0.812  0.372
Condition:Sex  1   0.00  0.0029   0.004  0.950
Residuals     47  33.96  0.7225               </code></pre>
</div>
</div>
<p>No significant difference between gender on learning achievement and math anxiety was found by gender.</p>
</section>
</section>
<section id="multiple-linear-regression" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Multiple Linear Regression</h1>
<p>We will be fitting a model to our data: one for predicting <code>Del_OverallAcc</code> and <code>Understand_avg</code>. The model uses following predictors:</p>
<ul>
<li><code>Condition</code></li>
<li><code>Sex</code></li>
<li><code>pretest</code></li>
<li><code>TMA_avg</code></li>
<li><code>MW_day1_avg</code> and <code>MW_day2_avg</code></li>
<li><code>SI_avg</code></li>
<li>Interaction Terms: <code>Condition*Sex</code>, <code>Condition*TMA_avg</code>, <code>Condition*TMA_avg*Sex</code></li>
</ul>
<p>To answer our research question we are interested in answering these hypotheses:</p>
<p><span class="math inline">H_0</span>: <span class="math inline">\beta_{Condition*Sex} = 0</span></p>
<p><span class="math inline">H_1</span>: <span class="math inline">\beta_{Condition*Sex} \neq 0</span>, interaction term between <code>Condition</code> and <code>Sex</code> is significant</p>
<section id="posttest-accuracy-scores" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="posttest-accuracy-scores"><span class="header-section-number">5.1</span> Posttest Accuracy Scores</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there's any participant missing accuracy score data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span> <span class="fu">count</span>(<span class="fu">is.na</span>(Del_OverallAcc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `is.na(Del_OverallAcc)`     n
  &lt;lgl&gt;                   &lt;int&gt;
1 FALSE                     229</code></pre>
</div>
</div>
<p>Every participant has a <code>Del_OverallAcc</code> data, now we fit the model to our data to predict <code>Del_OverallAcc</code>:</p>
<section id="chicago-data-1" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="chicago-data-1"><span class="header-section-number">5.1.1</span> Chicago Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>m2_c <span class="ot">&lt;-</span> Del_OverallAcc <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> pretest <span class="sc">+</span> TMA_avg <span class="sc">+</span> MW_day1_avg <span class="sc">+</span> MW_day2_avg <span class="sc">+</span> SI_avg <span class="sc">+</span> Condition<span class="sc">*</span>Sex <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg<span class="sc">*</span>Sex</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>fit2_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(m2_c, <span class="at">data =</span> df_c)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = m2_c, data = df_c)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38202 -0.11161  0.01092  0.11122  0.43224 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              0.542110   0.127319   4.258 3.50e-05 ***
Condition1              -0.232235   0.123656  -1.878   0.0622 .  
Sex1                     0.014247   0.122861   0.116   0.9078    
pretest                  0.162358   0.030644   5.298 3.79e-07 ***
TMA_avg                 -0.062432   0.042965  -1.453   0.1481    
MW_day1_avg              0.007828   0.022348   0.350   0.7266    
MW_day2_avg             -0.006590   0.022486  -0.293   0.7698    
SI_avg                   0.041714   0.017031   2.449   0.0154 *  
Condition1:Sex1          0.135935   0.169357   0.803   0.4234    
Condition1:TMA_avg       0.130047   0.058456   2.225   0.0275 *  
Sex1:TMA_avg            -0.002153   0.055738  -0.039   0.9692    
Condition1:Sex1:TMA_avg -0.101442   0.078400  -1.294   0.1976    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.182 on 161 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.2516,    Adjusted R-squared:  0.2005 
F-statistic: 4.922 on 11 and 161 DF,  p-value: 1.467e-06</code></pre>
</div>
</div>
<p><em>Significant Predictors:</em></p>
<ul>
<li><code>pretest</code> (p = 3.79e-07)</li>
<li><code>SI_avg</code> (p = 0.0154): While controlling for other predictors, every one unit increse in <code>SI_avg</code> results in 0.04 increase in <code>Del_OverallAcc</code></li>
<li><code>TMA_avg:Condition</code> (p = 0.0133): Students who received worked examples, while controlling for other predictors, had increase in <code>Del_OverallAcc</code> by 0.07 for every 1 unit increase in <code>TMA_avg</code>, while students who received worked examples had decrease in <code>Del_OverallAcc</code>.</li>
</ul>
</section>
<section id="irvine-data-1" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="irvine-data-1"><span class="header-section-number">5.1.2</span> Irvine Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>m2_i <span class="ot">&lt;-</span> Del_OverallAcc <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> pretest <span class="sc">+</span> TMA_avg <span class="sc">+</span> MW_day1_avg <span class="sc">+</span> MW_day2_avg <span class="sc">+</span> SI_avg <span class="sc">+</span> Condition<span class="sc">*</span>Sex <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg<span class="sc">*</span>Sex</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>fit2_i <span class="ot">&lt;-</span> <span class="fu">lm</span>(m2_i, <span class="at">data =</span> df_i)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = m2_i, data = df_i)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42790 -0.10182 -0.01513  0.14616  0.37472 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)              0.88724    0.28888   3.071  0.00398 **
Condition1              -0.26108    0.20083  -1.300  0.20164   
Sex1                    -0.13406    0.34425  -0.389  0.69919   
pretest                  0.07852    0.07096   1.106  0.27565   
TMA_avg                 -0.10707    0.08267  -1.295  0.20333   
MW_day1_avg             -0.02124    0.03247  -0.654  0.51698   
MW_day2_avg              0.00225    0.03811   0.059  0.95325   
SI_avg                  -0.04332    0.04888  -0.886  0.38117   
Condition1:Sex1          0.30904    0.44482   0.695  0.49154   
Condition1:TMA_avg       0.11815    0.09739   1.213  0.23275   
Sex1:TMA_avg            -0.01948    0.17680  -0.110  0.91285   
Condition1:Sex1:TMA_avg -0.07297    0.22574  -0.323  0.74833   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2098 on 37 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.2424,    Adjusted R-squared:  0.01722 
F-statistic: 1.076 on 11 and 37 DF,  p-value: 0.4055</code></pre>
</div>
</div>
<p><em>Significant Predictors</em></p>
<p>No significant factor was found</p>
<p>In both sites, we failed to reject the null. That is, we did not find enough evidence to prove that gender played significant effect on math anxiety and learning achievements.</p>
</section>
</section>
<section id="perceived-understanding" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="perceived-understanding"><span class="header-section-number">5.2</span> Perceived Understanding</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there's any participant missing understanding data</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span> <span class="fu">count</span>(<span class="fu">is.na</span>(Understand_avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  `is.na(Understand_avg)`     n
  &lt;lgl&gt;                   &lt;int&gt;
1 FALSE                     227
2 TRUE                        2</code></pre>
</div>
</div>
<p>2 participants were missing Understand_avg data (row #56 and #198)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill out missing understanding avg data with the group average</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>understand_avg1 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> Sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> chicago <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean_understand =</span> <span class="fu">mean</span>(Understand_avg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>understand_avg2 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> Sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> chicago <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean_understand =</span> <span class="fu">mean</span>(Understand_avg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># assign imputed value</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>df1[<span class="dv">56</span>, <span class="dv">17</span>] <span class="ot">=</span> understand_avg1</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>df1[<span class="dv">198</span>, <span class="dv">17</span>] <span class="ot">=</span> understand_avg1</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># update chicago and irvine data</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>df_c <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>df_i <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Every participant now has a <code>Understand_avg</code> data, now we fit the model to our data to predict <code>Understand_avg</code>:</p>
<section id="chicago-data-2" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="chicago-data-2"><span class="header-section-number">5.2.1</span> Chicago Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>m3_c <span class="ot">&lt;-</span> Understand_avg <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> pretest <span class="sc">+</span> TMA_avg <span class="sc">+</span> MW_day1_avg <span class="sc">+</span> MW_day2_avg <span class="sc">+</span> SI_avg <span class="sc">+</span> Condition<span class="sc">*</span>Sex <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg<span class="sc">*</span>Sex</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>fit3_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(m3_c, <span class="at">data =</span> df_c)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = m3_c, data = df_c)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.433 -13.955   3.271  15.456  31.891 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)              68.89847   31.72636   2.172   0.0364 *
Condition1              -12.50162   22.05636  -0.567   0.5743  
Sex1                     31.56251   37.80707   0.835   0.4092  
pretest                  14.85494    7.79327   1.906   0.0644 .
TMA_avg                   2.19989    9.07967   0.242   0.8099  
MW_day1_avg               0.02901    3.56547   0.008   0.9936  
MW_day2_avg              -7.29219    4.18524  -1.742   0.0898 .
SI_avg                    3.66500    5.36770   0.683   0.4990  
Condition1:Sex1           2.68636   48.85190   0.055   0.9564  
Condition1:TMA_avg       -0.37717   10.69578  -0.035   0.9721  
Sex1:TMA_avg            -22.96981   19.41642  -1.183   0.2444  
Condition1:Sex1:TMA_avg   4.96932   24.79190   0.200   0.8422  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 23.04 on 37 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3389,    Adjusted R-squared:  0.1424 
F-statistic: 1.725 on 11 and 37 DF,  p-value: 0.106</code></pre>
</div>
</div>
<p>No significant predictor was found in predicting <code>Understand_avg</code>.</p>
</section>
<section id="irvine-data-2" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="irvine-data-2"><span class="header-section-number">5.2.2</span> Irvine Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>m3_i <span class="ot">&lt;-</span> Understand_avg <span class="sc">~</span> Condition <span class="sc">+</span> Sex <span class="sc">+</span> pretest <span class="sc">+</span> TMA_avg <span class="sc">+</span> MW_day1_avg <span class="sc">+</span> MW_day2_avg <span class="sc">+</span> SI_avg <span class="sc">+</span> Condition<span class="sc">*</span>Sex <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg <span class="sc">+</span> Condition<span class="sc">*</span>TMA_avg<span class="sc">*</span>Sex</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>fit3_i <span class="ot">&lt;-</span> <span class="fu">lm</span>(m3_i, <span class="at">data =</span> df_i)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = m3_i, data = df_i)

Residuals:
    Min      1Q  Median      3Q     Max 
-63.135  -7.494   3.053  11.612  36.162 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              63.0654    12.7276   4.955 1.82e-06 ***
Condition1                7.0304    12.3614   0.569   0.5703    
Sex1                      3.7567    12.2820   0.306   0.7601    
pretest                   8.8502     3.0634   2.889   0.0044 ** 
TMA_avg                  -0.5401     4.2950  -0.126   0.9001    
MW_day1_avg              -5.1670     2.2340  -2.313   0.0220 *  
MW_day2_avg              -1.2960     2.2479  -0.577   0.5651    
SI_avg                    7.2430     1.7025   4.254 3.55e-05 ***
Condition1:Sex1          -6.3660    16.9300  -0.376   0.7074    
Condition1:TMA_avg       -3.6694     5.8436  -0.628   0.5309    
Sex1:TMA_avg             -1.1626     5.5719  -0.209   0.8350    
Condition1:Sex1:TMA_avg   3.8474     7.8374   0.491   0.6242    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.19 on 161 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.3031,    Adjusted R-squared:  0.2555 
F-statistic: 6.366 on 11 and 161 DF,  p-value: 1.05e-08</code></pre>
</div>
</div>
<p><em>Significant Predictors</em></p>
<p><code>pretest</code> (p = 0.0044)</p>
<p><code>MW_day1_avg</code> (p = .0220): While controlling for other predictors, every 1 unit of increase in <code>MW_day1_avg</code> decreases perceived understanding by 5.1670.</p>
<p><code>SI_avg</code> (p = 3.55e-05): While controlling for other predictors, every 1 unit of increase in <code>SI_avg</code> increases perceived understanding by 7.2430.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display result as a table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="results" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="results"><span class="header-section-number">5.3</span> Results</h2>
<p>No significant effect was found by gender on either math anxiety or learning achievements</p>
<p>However, we saw that worked examples were overall effective in reducing the effect of math anxiety on posttest accuracy scores, regardless of gender but only in Chicago.</p>
<p>No significant effect was found by math anxiety on perceived understanding. Instead, mind wandering and situational interest were two dominant significant predictors, but only in Irvine.</p>
<p>Students in Chicago significantly performed worst in learning achievements</p>
</section>
</section>
<section id="path-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Path Analysis</h1>
<p>We constructed structural equation models to model learning achievements: <code>Del_OverallAcc</code> and <code>Understand_avg</code>. We fit the model for each site data (<code>df_c</code> and <code>df_i</code>), and chi-square test was used to determine if the free model was significantly different from the constrined model.</p>
<section id="posttest-acucracy-scores" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="posttest-acucracy-scores"><span class="header-section-number">6.1</span> Posttest Acucracy Scores</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model definition</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>m_acc <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="st">  TMA_avg ~ 1 + MW_day1_avg + MW_day2_avg + SI_avg + Condition</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Del_OverallAcc ~ 1 + TMA_avg + Condition</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="chicago-data-3" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="chicago-data-3"><span class="header-section-number">6.1.1</span> Chicago Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free model</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>fit_ca <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_c, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># constrained model</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>fit_ca_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if the constrained and free models are significantly diff</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_ca, fit_ca_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)
fit_ca    6 103.53 141.37  5.184                                      
fit_ca_c 14 100.30 123.00 17.958     12.774 0.15606       8     0.1199</code></pre>
</div>
</div>
<p>No significant difference between the free and constrained models for Chicago in modeling <code>Del_OverallAcc</code>.</p>
</section>
<section id="irvine-data-3" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="irvine-data-3"><span class="header-section-number">6.1.2</span> Irvine Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free model</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>fit_ia <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_i, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co"># constrained model</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>fit_ia_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_ia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.15 ended normally after 65 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        20

  Number of observations per group:               Used       Total
    0                                               69          72
    1                                              104         106

Model Test User Model:
                                                      
  Test statistic                                 5.818
  Degrees of freedom                                 6
  P-value (Chi-square)                           0.444
  Test statistic for each group:
    0                                            2.992
    1                                            2.826

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  TMA_avg ~                                           
    MW_day1_avg       0.366    0.163    2.244    0.025
    MW_day2_avg      -0.261    0.157   -1.669    0.095
    SI_avg           -0.126    0.101   -1.252    0.211
    Condition        -0.042    0.175   -0.238    0.812
  Del_OverallAcc ~                                    
    TMA_avg           0.014    0.033    0.432    0.666
    Condition         0.045    0.051    0.876    0.381

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .TMA_avg           2.136    0.543    3.936    0.000
   .Del_OverallAcc    0.595    0.108    5.484    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .TMA_avg           0.501    0.085    5.874    0.000
   .Del_OverallAcc    0.044    0.008    5.874    0.000


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  TMA_avg ~                                           
    MW_day1_avg       0.069    0.093    0.744    0.457
    MW_day2_avg       0.367    0.089    4.104    0.000
    SI_avg           -0.016    0.077   -0.214    0.830
    Condition         0.010    0.128    0.081    0.935
  Del_OverallAcc ~                                    
    TMA_avg          -0.078    0.025   -3.161    0.002
    Condition        -0.033    0.037   -0.895    0.371

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .TMA_avg           1.325    0.437    3.030    0.002
   .Del_OverallAcc    0.871    0.081   10.743    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .TMA_avg           0.407    0.056    7.211    0.000
   .Del_OverallAcc    0.035    0.005    7.211    0.000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if the constrained and free models are significantly diff</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_ia, fit_ia_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC   Chisq Chisq diff  RMSEA Df diff Pr(&gt;Chisq)   
fit_ia    6 316.47 379.54  5.8179                                        
fit_ia_c 14 322.74 360.58 28.0876      22.27 0.1436       8    0.00444 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Chi-squared difference test showed a significant result (p = 0.004444), which indicated that free model and constrained models are significantly different. Now, we need to see which predictors are different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>m_a2 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="st">  TMA_avg ~ 1 + MW_day1_avg + MW_day2_avg + SI_avg + Condition</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="st">  Del_OverallAcc ~ 1 + c("b1", "b1") * TMA_avg + Condition</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>fit_ia2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_a2, df_i, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_ia2, fit_ia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

        Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit_ia   6 316.47 379.54  5.8179                                        
fit_ia2  7 319.33 379.25 10.6785     4.8606 0.21126       1    0.02748 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We find that the models are still significantly different, implying that the path between <code>TMA_avg</code> -&gt; <code>Del_OverallAcc</code> should not be constrained and instead that it should be left to vary among gender.</p>
</section>
<section id="visualize-results" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="visualize-results"><span class="header-section-number">6.1.3</span> Visualize Results</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chicago</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit_ca,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"Math</span><span class="sc">\n</span><span class="st">Anxiety"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"MW 1"</span>,<span class="st">"MW 2"</span>, <span class="st">"SI"</span>, <span class="st">"Condition"</span>),</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Irvine</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit_ia,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"Math</span><span class="sc">\n</span><span class="st">Anxiety"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"MW 1"</span>,<span class="st">"MW 2"</span>, <span class="st">"SI"</span>, <span class="st">"Condition"</span>),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-26-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-26-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="perceived-understanding-1" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="perceived-understanding-1"><span class="header-section-number">6.2</span> Perceived Understanding</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model definition</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>m_und <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="st">  TMA_avg ~ 1 + MW_day1_avg + MW_day2_avg + SI_avg + Condition</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Understand_avg ~ 1 + TMA_avg + Condition</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="chicago-data-4" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="chicago-data-4"><span class="header-section-number">6.2.1</span> Chicago Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free model</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>fit_cu <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_c, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># constrained model</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>fit_cu_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if the constrained and free models are significantly diff</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_cu, fit_cu_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit_cu    6 567.75 605.58 11.625                                        
fit_cu_c 14 566.69 589.39 26.569     14.944 0.18822       8    0.06025 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No significant difference between the free and constrained models for Chicago in modeling <code>Understand_avg</code>.</p>
</section>
<section id="irvine-data-4" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="irvine-data-4"><span class="header-section-number">6.2.2</span> Irvine Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>fit_iu <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_i, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># constrained model</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>fit_iu_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if the constrained and free models are significantly diff</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_iu, fit_iu_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit_iu    6 1923.7 1986.7 46.057                                        
fit_iu_c 14 1923.7 1961.6 62.151     16.094 0.10815       8    0.04106 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Chi-squared difference test showed a significant result (p = 0.004444), which indicated that free model and constrained models are significantly different. Now, we need to see which predictors are different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>m_u2 <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="st">  TMA_avg ~ 1 + MW_day1_avg + MW_day2_avg + SI_avg + Condition</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="st">  Understand_avg ~ 1 + c("b1", "b1") * TMA_avg + Condition</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fit_iu2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_u2, df_i, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_iu2, fit_iu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

        Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
fit_iu   6 1923.7 1986.7 46.057                                    
fit_iu2  7 1921.8 1981.8 46.252    0.19469     0       1      0.659</code></pre>
</div>
</div>
<p>In this case, there is not a significant difference between the two models (P = 0.659), implying that there is no difference in the fit of the constrained model and the unconstrained model and that this constraint is valid.</p>
</section>
<section id="visualize-results-1" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="visualize-results-1"><span class="header-section-number">6.2.3</span> Visualize Results</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chicago</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit_cu,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"Math</span><span class="sc">\n</span><span class="st">Anxiety"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"MW 1"</span>,<span class="st">"MW 2"</span>, <span class="st">"SI"</span>, <span class="st">"Condition"</span>),</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-34-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Irvine</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit_iu,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"Math</span><span class="sc">\n</span><span class="st">Anxiety"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"MW 1"</span>,<span class="st">"MW 2"</span>, <span class="st">"SI"</span>, <span class="st">"Condition"</span>),</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-34-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling-final_files/figure-html/unnamed-chunk-34-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>