<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emi Cervantes">

<title>Path Analysis w/ Moderation Effect</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="modeling6_files/libs/clipboard/clipboard.min.js"></script>
<script src="modeling6_files/libs/quarto-html/quarto.js"></script>
<script src="modeling6_files/libs/quarto-html/popper.min.js"></script>
<script src="modeling6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="modeling6_files/libs/quarto-html/anchor.min.js"></script>
<link href="modeling6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="modeling6_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="modeling6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="modeling6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="modeling6_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#path-analysis-w-moderation-effect" id="toc-path-analysis-w-moderation-effect" class="nav-link active" data-scroll-target="#path-analysis-w-moderation-effect"><span class="header-section-number">1</span> Path Analysis w/ Moderation Effect</a>
  <ul class="collapse">
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link" data-scroll-target="#load-libraries"><span class="header-section-number">1.1</span> Load Libraries</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data"><span class="header-section-number">1.2</span> Load Data</a>
  <ul class="collapse">
  <li><a href="#data-clearning-raw-data" id="toc-data-clearning-raw-data" class="nav-link" data-scroll-target="#data-clearning-raw-data"><span class="header-section-number">1.2.1</span> Data Clearning (raw data)</a></li>
  <li><a href="#data-cleaning-clean-data" id="toc-data-cleaning-clean-data" class="nav-link" data-scroll-target="#data-cleaning-clean-data"><span class="header-section-number">1.2.2</span> Data Cleaning (clean data)</a></li>
  <li><a href="#final-sample-size-for-data-analysismodeling" id="toc-final-sample-size-for-data-analysismodeling" class="nav-link" data-scroll-target="#final-sample-size-for-data-analysismodeling"><span class="header-section-number">1.2.3</span> Final Sample Size for Data Analysis/Modeling</a></li>
  </ul></li>
  <li><a href="#gender-differences-in-tma-and-mw" id="toc-gender-differences-in-tma-and-mw" class="nav-link" data-scroll-target="#gender-differences-in-tma-and-mw"><span class="header-section-number">1.3</span> Gender Differences in TMA and MW</a>
  <ul class="collapse">
  <li><a href="#trait-math-anxiety" id="toc-trait-math-anxiety" class="nav-link" data-scroll-target="#trait-math-anxiety"><span class="header-section-number">1.3.1</span> Trait Math Anxiety</a></li>
  <li><a href="#mind-wandering" id="toc-mind-wandering" class="nav-link" data-scroll-target="#mind-wandering"><span class="header-section-number">1.3.2</span> Mind Wandering</a></li>
  </ul></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">1.4</span> Modeling</a>
  <ul class="collapse">
  <li><a href="#overall-accuracy" id="toc-overall-accuracy" class="nav-link" data-scroll-target="#overall-accuracy"><span class="header-section-number">1.4.1</span> Overall Accuracy</a></li>
  <li><a href="#perceived-understanding" id="toc-perceived-understanding" class="nav-link" data-scroll-target="#perceived-understanding"><span class="header-section-number">1.4.2</span> Perceived Understanding</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="modeling6.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="modeling6.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Path Analysis w/ Moderation Effect</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emi Cervantes </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="path-analysis-w-moderation-effect" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Path Analysis w/ Moderation Effect</h1>
<section id="load-libraries" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="load-libraries"><span class="header-section-number">1.1</span> Load Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-16
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
</div>
</section>
<section id="load-data" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="load-data"><span class="header-section-number">1.2</span> Load Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(<span class="st">'../../../data/math-anxiety-raw-data.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `Subject ID #` -&gt; `Subject ID #...8`
• `Subject ID #` -&gt; `Subject ID #...9`
• `StartDate` -&gt; `StartDate...11`
• `EndDate` -&gt; `EndDate...12`
• `Progress` -&gt; `Progress...13`
• `Duration (in seconds)` -&gt; `Duration (in seconds)...17`
• `Finished` -&gt; `Finished...18`
• `RecordedDate` -&gt; `RecordedDate...19`
• `Browser_info_Browser` -&gt; `Browser_info_Browser...20`
• `Browser_info_Version` -&gt; `Browser_info_Version...21`
• `Browser_info_Operating System` -&gt; `Browser_info_Operating System...22`
• `Browser_info_Resolution` -&gt; `Browser_info_Resolution...23`
• `Misc_0` -&gt; `Misc_0...36`
• `Misc_1` -&gt; `Misc_1...100`
• `Misc_2` -&gt; `Misc_2...145`
• `MW_control_1` -&gt; `MW_control_1...210`
• `MW_control_2` -&gt; `MW_control_2...211`
• `MW_control_3` -&gt; `MW_control_3...212`
• `MW_control_4` -&gt; `MW_control_4...213`
• `MW_control_5` -&gt; `MW_control_5...214`
• `` -&gt; `...219`
• `StartDate` -&gt; `StartDate...221`
• `EndDate` -&gt; `EndDate...222`
• `Progress` -&gt; `Progress...223`
• `Duration (in seconds)` -&gt; `Duration (in seconds)...224`
• `Finished` -&gt; `Finished...225`
• `RecordedDate` -&gt; `RecordedDate...226`
• `Browser_info_Browser` -&gt; `Browser_info_Browser...227`
• `Browser_info_Version` -&gt; `Browser_info_Version...228`
• `Browser_info_Operating System` -&gt; `Browser_info_Operating System...229`
• `Browser_info_Resolution` -&gt; `Browser_info_Resolution...230`
• `Misc_0` -&gt; `Misc_0...232`
• `Misc_1` -&gt; `Misc_1...239`
• `Misc_2` -&gt; `Misc_2...290`
• `MW_control_1` -&gt; `MW_control_1...295`
• `MW_control_2` -&gt; `MW_control_2...296`
• `MW_control_3` -&gt; `MW_control_3...297`
• `MW_control_4` -&gt; `MW_control_4...298`
• `MW_control_5` -&gt; `MW_control_5...299`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'../../../data/affectoutcome_norm_predict_1102.csv'</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 409
   drop dropwhy        incomplete_pt1 incomplete_pt2 `did not do_pt2`
  &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
1    NA &lt;NA&gt;                       NA              1               NA
2    NA &lt;NA&gt;                       NA             NA               NA
3     1 duplicate pt 1             NA             NA               NA
4    NA &lt;NA&gt;                       NA             NA               NA
5    NA &lt;NA&gt;                       NA             NA               NA
6    NA &lt;NA&gt;                       NA             NA               NA
# ℹ 404 more variables: `Scratch paper_pt1` &lt;dbl&gt;, `Scratch paper_pt2` &lt;dbl&gt;,
#   `Subject ID #...8` &lt;chr&gt;, `Subject ID #...9` &lt;chr&gt;, Notes &lt;chr&gt;,
#   StartDate...11 &lt;dttm&gt;, EndDate...12 &lt;dttm&gt;, Progress...13 &lt;dbl&gt;,
#   Condition &lt;chr&gt;, `UPDATED_Opt-in-out` &lt;dbl&gt;, Opt_Out &lt;chr&gt;,
#   `Duration (in seconds)...17` &lt;dbl&gt;, Finished...18 &lt;dbl&gt;,
#   RecordedDate...19 &lt;dttm&gt;, Browser_info_Browser...20 &lt;chr&gt;,
#   Browser_info_Version...21 &lt;chr&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X subjectid race_rv gender chicago base_enjoy base_worry tma_sum_rv
1 1     Aq001       1      0       1          0          2  11.000000
2 2    Aq002a       4      0       1          3          1  10.000000
3 3     Aq003       4      0       1          4          3   9.000000
4 4     Aq004       4      0       1          3          1   8.000000
5 5    Aq005a       4      1       1          4          1   8.000000
6 6     Aq006       4      1       1          4          1   8.179096
  cries_sum_rv worry_durimm_avg worry_del_avg enjoy_del_avg enjoy_durimm_avg
1            8         1.833330     2.0000000      2.000000          1.33333
2            4         0.166667     0.0000000      4.000000          3.50000
3           10         2.666670     0.6666670      1.333330          3.16667
4            6         0.333333     1.0000000      1.333330          1.50000
5            5         1.166670     0.0000000      3.666670          3.33333
6            5         0.333333     0.3728205      2.778308          3.16667
  understand_avg mw_day1_sum mw_day2_sum   si_sum
1        78.5714          15   13.418452 39.92667
2        81.4286          11    8.000000 54.00000
3        83.8571          10    9.000000 36.00000
4        84.2857          15    8.000000 39.00000
5        66.0000          10   10.000000 54.00000
6        27.4286           7    8.708517 47.03650</code></pre>
</div>
</div>
<section id="data-clearning-raw-data" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="data-clearning-raw-data"><span class="header-section-number">1.2.1</span> Data Clearning (raw data)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>tma_lst <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"TMA_1"</span>, <span class="st">"TMA_2"</span>, <span class="st">"TMA_3"</span>,<span class="st">"TMA_4"</span>, <span class="st">"TMA_5"</span>, <span class="st">"TMA_6"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>             <span class="st">"TMA_sum"</span>, <span class="st">"TMA_avg"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">9</span>,Condition, Sex, chicago, nonwhite, pretest,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>              MW_day1_avg, MW_day2_avg, SI_avg, tma_lst,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>              Understand_avg, Del_OverallAcc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %&gt;% select(tma_lst)

  # Now:
  data %&gt;% select(all_of(tma_lst))

See &lt;https://tidyselect.r-lib.org/reference/faq-external-vector.html&gt;.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get rid of row that has NA values in Condition and/or Sex</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> Condition <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sex))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Condition[df2<span class="sc">$</span>Condition <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign 0 for "boy" and 1 for "girl"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Sex[df2<span class="sc">$</span>Sex <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Sex[df2<span class="sc">$</span>Sex <span class="sc">==</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure variable is categorical</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>chicago <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df2<span class="sc">$</span>chicago)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Sex <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df2<span class="sc">$</span>Sex)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>nonwhite <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df2<span class="sc">$</span>nonwhite)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Condition <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df2<span class="sc">$</span>Condition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Add MW average</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">MW_avg =</span> <span class="fu">rowMeans</span>(df2[<span class="dv">6</span><span class="sc">:</span><span class="dv">7</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df2[<span class="dv">19</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  Del_OverallAcc
           &lt;dbl&gt;
1          0.367
2          0.9  
3          0.5  
4          0.6  
5          0.167
6          0.267</code></pre>
</div>
</div>
</section>
<section id="data-cleaning-clean-data" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="data-cleaning-clean-data"><span class="header-section-number">1.2.2</span> Data Cleaning (clean data)</h3>
<p>The clean, imputed data provided contains <code>_sum</code> variable only for both <code>TMA</code>, <code>MW</code>, and <code>SI</code>. We want avaerage values for both math anxiety, mind wandering, and situational interest.</p>
<ul>
<li><p>Trait math anxiety: 6 questions</p></li>
<li><p>Mind wandering: 12 questions</p></li>
<li><p>Situational interest: 14 questions</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># average trait math anxiety</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">TMA_avg =</span> tma_sum_rv <span class="sc">/</span> <span class="dv">6</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># average mind wandering</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">MW_avg =</span> ( mw_day1_sum <span class="sc">+</span> mw_day2_sum ) <span class="sc">/</span> <span class="dv">12</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># average situational interest</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">SI_avg =</span> si_sum <span class="sc">/</span> <span class="dv">14</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also need to add students’ accuracy scores to this dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df2)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"subjectid"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">1</span>,<span class="dv">19</span>,<span class="dv">2</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>df_clean2 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(df_clean, df3, <span class="at">by =</span> <span class="st">"subjectid"</span>) <span class="sc">%&gt;%</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Del_OverallAcc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_clean2n <span class="ot">&lt;-</span> df_clean2</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># standarize data</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df_clean2[<span class="dv">6</span><span class="sc">:</span><span class="dv">21</span>] <span class="ot">&lt;-</span> df_clean2[<span class="dv">6</span><span class="sc">:</span><span class="dv">21</span>] <span class="sc">%&gt;%</span> <span class="fu">mutate_all</span>(<span class="sc">~</span>(<span class="fu">scale</span>(.) <span class="sc">%&gt;%</span> as.vector))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_clean2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X subjectid race_rv gender chicago base_enjoy base_worry  tma_sum_rv
1 2    Aq002a       4      0       1  0.3134152  0.1901180  0.05565683
2 3     Aq003       4      0       1  1.3230243  2.4315095 -0.19368576
3 4     Aq004       4      0       1  0.3134152  0.1901180 -0.44302836
4 5    Aq005a       4      1       1  1.3230243  0.1901180 -0.44302836
5 7     Aq007       4      1       1  0.3134152 -0.9305777 -0.19368576
6 8     Aq008       1      1       1  1.3230243 -0.9305777 -0.19368576
  cries_sum_rv worry_durimm_avg worry_del_avg enjoy_del_avg enjoy_durimm_avg
1  -0.53125688      -0.79696635  -0.719735270     1.4815633        1.2233993
2   1.20906499       2.03519738   0.004852649    -0.7383067        0.8886751
3   0.04885041      -0.60815642   0.367146064    -0.7383067       -0.7849662
4  -0.24120323       0.33590118  -0.719735270     1.2040827        1.0560322
5  -1.11136417      -0.04172435   0.004852649     1.2040827        0.8886751
6  -1.11136417      -0.98577742  -0.719735270     1.4815633        1.7254907
  understand_avg mw_day1_sum mw_day2_sum     si_sum     TMA_avg      MW_avg
1      0.1674838 -0.02169112 -0.28024879  1.0673033  0.05565683 -0.16627534
2      0.2748604 -0.21850195 -0.07839757 -0.5462576 -0.19368576 -0.16627534
3      0.2938111  0.76555218 -0.28024879 -0.2773308 -0.44302836  0.27753804
4     -0.5146949 -0.21850195  0.12345365  1.0673033 -0.44302836 -0.05532199
5     -1.3800484 -0.41531278 -0.68395124  1.3362302 -0.19368576 -0.61008871
6      0.4769902 -1.00574525 -0.68395124  1.1569456 -0.19368576 -0.94294874
      SI_avg Del_OverallAcc Condition
1  1.0673033    -1.11122924         1
2 -0.5462576     1.24079296         1
3 -0.2773308    -0.52322369         1
4  1.0673033    -0.08221953         1
5  1.3362302    -1.99323756         0
6  1.1569456    -1.55223340         1</code></pre>
</div>
</div>
</section>
<section id="final-sample-size-for-data-analysismodeling" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="final-sample-size-for-data-analysismodeling"><span class="header-section-number">1.2.3</span> Final Sample Size for Data Analysis/Modeling</h3>
<section id="overall-descriptive" class="level4" data-number="1.2.3.1">
<h4 data-number="1.2.3.1" class="anchored" data-anchor-id="overall-descriptive"><span class="header-section-number">1.2.3.1</span> Overall Descriptive</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(df_clean2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">df_clean2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">224</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">subjectid</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">224</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">140.21</td>
<td style="text-align: right;">80.99</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">65.75</td>
<td style="text-align: right;">149.50</td>
<td style="text-align: right;">207.25</td>
<td style="text-align: right;">280.00</td>
<td style="text-align: left;">▇▇▆▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">race_rv</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▅▁▃▃▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▆▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">chicago</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">base_enjoy</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-2.72</td>
<td style="text-align: right;">-0.70</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">1.32</td>
<td style="text-align: left;">▁▁▇▇▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">base_worry</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.93</td>
<td style="text-align: right;">-0.93</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: left;">▇▇▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tma_sum_rv</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.19</td>
<td style="text-align: right;">-0.69</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">cries_sum_rv</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.69</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: left;">▅▆▇▃▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">worry_durimm_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.99</td>
<td style="text-align: right;">-0.80</td>
<td style="text-align: right;">-0.23</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">3.36</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">worry_del_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.72</td>
<td style="text-align: right;">-0.72</td>
<td style="text-align: right;">-0.36</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">enjoy_del_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.85</td>
<td style="text-align: right;">-0.74</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: left;">▅▂▇▅▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">enjoy_durimm_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-2.29</td>
<td style="text-align: right;">-0.66</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">1.73</td>
<td style="text-align: left;">▂▅▇▇▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">understand_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-3.17</td>
<td style="text-align: right;">-0.51</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">▁▁▂▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">mw_day1_sum</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.20</td>
<td style="text-align: right;">-0.61</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: left;">▇▆▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mw_day2_sum</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.89</td>
<td style="text-align: right;">-0.68</td>
<td style="text-align: right;">-0.28</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">si_sum</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-2.70</td>
<td style="text-align: right;">-0.55</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: left;">▂▃▅▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TMA_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.19</td>
<td style="text-align: right;">-0.69</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: left;">▇▃▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">MW_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.17</td>
<td style="text-align: right;">-0.72</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SI_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-2.70</td>
<td style="text-align: right;">-0.55</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: left;">▂▃▅▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del_OverallAcc</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-2.43</td>
<td style="text-align: right;">-0.67</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">1.68</td>
<td style="text-align: left;">▂▅▆▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Condition</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Full sample size after preprocessing: <span class="math inline">n = 224</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>control_n <span class="ot">&lt;-</span> df_clean2 <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago, gender) <span class="sc">%&gt;%</span> <span class="fu">count</span>()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>exp_n <span class="ot">&lt;-</span> df_clean2 <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago, gender) <span class="sc">%&gt;%</span> <span class="fu">count</span>()</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">rbind</span>(<span class="fu">t</span>(control_n[<span class="dv">3</span>]),<span class="fu">t</span>(exp_n[<span class="dv">3</span>]))) <span class="sc">%&gt;%</span> remove_rownames </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="st">"No Worked EX"</span>, <span class="st">"Worked EX"</span>), sample_size)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> sample_size <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Total =</span>  <span class="fu">rowSums</span>(sample_size[<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])) <span class="sc">%&gt;%</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sample_size) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Condition"</span>, <span class="st">"Boy-I"</span>, <span class="st">"Girl-I"</span>, <span class="st">"Boy-C"</span>, <span class="st">"Girl-C"</span>, <span class="st">"Total"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Condition Boy-I Girl-I Boy-C Girl-C Total
1 No Worked EX    34     51    10     14   109
2    Worked EX    34     55    17      9   115
3        Total    68    106    27     23   224</code></pre>
</div>
</div>
<p>Total number of samples in data: <span class="math inline">n = 224</span></p>
<ul>
<li>Number of samples in No Worked EX group: <span class="math inline">n_{c} = 109</span>
<ul>
<li>Girls: <span class="math inline">n_{c,g} = 65</span></li>
<li>Boys: <span class="math inline">n_{c,b} = 44</span></li>
</ul></li>
<li>Number of samples in Worked EX group: <span class="math inline">n_{ex} = 115</span>
<ul>
<li>Girls: <span class="math inline">n_{c,g} = 64</span></li>
<li>Boys: <span class="math inline">n_{c,b} = 51</span></li>
</ul></li>
</ul>
</section>
<section id="ethnicity-descriptive" class="level4" data-number="1.2.3.2">
<h4 data-number="1.2.3.2" class="anchored" data-anchor-id="ethnicity-descriptive"><span class="header-section-number">1.2.3.2</span> Ethnicity Descriptive</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ethnicity descriptives</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df_clean2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(race_rv) <span class="sc">%&gt;%</span> <span class="fu">count</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(df_clean2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
# Groups:   race_rv [5]
  race_rv     n      p
    &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
1       1    48 0.214 
2       2     7 0.0312
3       3    41 0.183 
4       4    41 0.183 
5       5    87 0.388 </code></pre>
</div>
</div>
<p>Summary:</p>
<ul>
<li>21% white (48)</li>
<li>3% black (7)</li>
<li>18% Asian/Pacific Islander (41)</li>
<li>18% Hispanic/Latinx (41)</li>
<li>39% Mixed race/other (87)</li>
</ul>
</section>
</section>
</section>
<section id="gender-differences-in-tma-and-mw" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="gender-differences-in-tma-and-mw"><span class="header-section-number">1.3</span> Gender Differences in TMA and MW</h2>
<section id="trait-math-anxiety" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="trait-math-anxiety"><span class="header-section-number">1.3.1</span> Trait Math Anxiety</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cond <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"No Worked EX"</span>, <span class="st">"Worked EX"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cond) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>location <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Irvine"</span>, <span class="st">"Chicago"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(location) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TMA mean by site, condition, and gender</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago, Condition,gender) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(TMA_avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'chicago', 'Condition'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># math anxiety density plot</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df_clean2n <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TMA_avg, <span class="at">fill =</span> <span class="fu">as.factor</span>(gender),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data=</span>mu, <span class="fu">aes</span>(<span class="at">xintercept=</span>mean, <span class="at">color=</span>as.factor</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                          (gender)),<span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Condition),</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">cols =</span> <span class="fu">vars</span>(chicago),</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Math Anxiety"</span>, <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Gender"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) <span class="sc">+</span><span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Overall, all students seemed to have a low average math anxiety (1 ~ 2). In Irvine, girls seemed to have higher math average than boys in both condition. However, in Chicago, boys seemed to have higher average than girls.</p>
<p>Girls seemed to have a higher math anxiety compared to boys overall. Check if the difference is significant in each site by using ANOVA test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span>  <span class="fu">aov</span>(TMA_avg <span class="sc">~</span> Condition <span class="sc">+</span> gender <span class="sc">+</span> chicago <span class="sc">+</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>             Condition<span class="sc">*</span>gender <span class="sc">+</span> Condition<span class="sc">*</span>gender<span class="sc">*</span>chicago,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_clean2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Df Sum Sq Mean Sq F value Pr(&gt;F)
Condition                  1   0.60  0.6047   0.596  0.441
gender                     1   0.29  0.2865   0.283  0.596
chicago                    1   0.37  0.3670   0.362  0.548
Condition:gender           1   0.01  0.0051   0.005  0.943
Condition:chicago          1   0.47  0.4705   0.464  0.496
gender:chicago             1   2.18  2.1788   2.149  0.144
Condition:gender:chicago   1   0.11  0.1053   0.104  0.748
Residuals                216 218.98  1.0138               </code></pre>
</div>
</div>
<p>No significant difference between gender on math anxiety was found by gender.</p>
</section>
<section id="mind-wandering" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="mind-wandering"><span class="header-section-number">1.3.2</span> Mind Wandering</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TMA mean by site, condition, and gender</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(chicago, Condition,gender) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(MW_avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'chicago', 'Condition'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># math anxiety density plot</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df_clean2n <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> MW_avg, <span class="at">fill =</span> <span class="fu">as.factor</span>(gender),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data=</span>mu, <span class="fu">aes</span>(<span class="at">xintercept=</span>mean, <span class="at">color=</span>as.factor</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>                          (gender)),<span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Condition),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">cols =</span> <span class="fu">vars</span>(chicago),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mind Wandering"</span>, <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Gender"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) <span class="sc">+</span><span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In Irvine, both girls and boys seemed to have similar low average mind wandering (1~2); worked example group showing somewhat higher mind wandering average than the worked example students in Irvine. On the other hand, in Chicago, boys had higher mind wandering than boys in both groups.</p>
<p>Check if the difference is significant in each site by using ANOVA test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span>  <span class="fu">aov</span>(MW_avg <span class="sc">~</span> Condition <span class="sc">+</span> gender <span class="sc">+</span> chicago <span class="sc">+</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>             Condition<span class="sc">*</span>gender <span class="sc">+</span> Condition<span class="sc">*</span>gender<span class="sc">*</span>chicago,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_clean2)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Df Sum Sq Mean Sq F value Pr(&gt;F)  
Condition                  1   5.24   5.241   5.335 0.0218 *
gender                     1   1.53   1.531   1.559 0.2132  
chicago                    1   0.43   0.432   0.440 0.5080  
Condition:gender           1   0.01   0.013   0.014 0.9071  
Condition:chicago          1   0.66   0.663   0.675 0.4121  
gender:chicago             1   1.58   1.582   1.610 0.2058  
Condition:gender:chicago   1   1.33   1.329   1.353 0.2461  
Residuals                216 212.21   0.982                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The results show that mind wandering was different between worked example and no worked example group, regardless of the cite location or gender. No gender difference was found in mind wandering.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the overall mind wandering average but by the condition</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>df_clean2n <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Condition) <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(MW_avg)) <span class="sc">%&gt;%</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(Condition), <span class="at">y =</span> mean)) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#ef476f"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">round</span>(mean,<span class="dv">2</span>)),  </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Mind Wandering by Condition"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Condition"</span>, <span class="at">y =</span> <span class="st">"Mind Wandeirng"</span>) <span class="sc">+</span> </span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"No WE Group"</span>, <span class="st">"WE Group"</span>)) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>WE group had a lower average mind wandering than no WE group.</p>
<section id="data-visualization" class="level4" data-number="1.3.2.1">
<h4 data-number="1.3.2.1" class="anchored" data-anchor-id="data-visualization"><span class="header-section-number">1.3.2.1</span> Data Visualization</h4>
<p>TMA vs Accuarcay Scores</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>tma_acc_plt <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TMA_avg, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> Del_OverallAcc, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Condition, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Math Anxiety vs Posttest Accuracy Score"</span>, </span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Anxiety"</span>, <span class="at">y =</span> <span class="st">"Overall Accuracy"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) </span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(tma_acc_plt, <span class="at">file =</span>  <span class="st">"../../../outputs/tma_acc_plt2.png"</span>,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tma_acc_plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>TMA vs Perceived Understanding</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>tma_und_plt <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TMA_avg, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> understand_avg, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Condition, </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Math Anxiety vs Perceived Understanding"</span>, </span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Anxiety"</span>, <span class="at">y =</span> <span class="st">"Perceived Understanding"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) </span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(tma_und_plt, <span class="at">file =</span>  <span class="st">"../../../outputs/tma_und_plt2.png"</span>,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>tma_und_plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>MW vs Posttest Accuracy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>mw_acc_plt <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> MW_avg, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">y =</span> Del_OverallAcc, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Condition, </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Mind Wandering vs Posttest Accuracy Score"</span>, </span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mind Wandering"</span>, <span class="at">y =</span> <span class="st">"Overall Accuracy"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(mw_acc_plt, <span class="at">file =</span>  <span class="st">"../../../outputs/mw_acc_plt2.png"</span>,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>mw_acc_plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>MW vs Perceived Understanding</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>mw_und_plt <span class="ot">&lt;-</span> df_clean2n <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> MW_avg, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> understand_avg, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Condition, </span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Mind Wandering vs Perceived Understanding"</span>, </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mind Wandering"</span>, <span class="at">y =</span> <span class="st">"Perceived Understanding"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>) </span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(mw_und_plt, <span class="at">file =</span>  <span class="st">"../../../outputs/mw_und_plt2.png"</span>,</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>mw_und_plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>TMA vs MW</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>tma_mw_plt <span class="ot">&lt;-</span> df_clean2 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> TMA_avg, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">y =</span> MW_avg, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="fu">as.factor</span>(gender))) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFC20A"</span>, <span class="st">"#0C7BDC"</span>), </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Boy"</span>, <span class="st">"Girl"</span>)) <span class="sc">+</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Condition, </span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">labeller =</span> <span class="fu">labeller</span>(<span class="at">Condition =</span> cond,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chicago =</span> location)) <span class="sc">+</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Math Anxiety vs Mind Wandering"</span>, </span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Anxiety"</span>, <span class="at">y =</span> <span class="st">"Mind Wandering"</span>, <span class="at">color =</span> <span class="st">"Gender"</span>)</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(tma_mw_plt, <span class="at">file =</span>  <span class="st">"../../../outputs/tma_mw_plt2.png"</span>,</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tma_mw_plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="modeling6_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="modeling" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="modeling"><span class="header-section-number">1.4</span> Modeling</h2>
<section id="overall-accuracy" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="overall-accuracy"><span class="header-section-number">1.4.1</span> Overall Accuracy</h3>
<p><strong>Model definition</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>m_acc <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + TMA_avg + SI_avg + gender + TMA_avg:gender</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="st">Del_OverallAcc ~ 1 + TMA_avg + MW_avg + SI_avg + gender + MW_avg:gender + TMA_avg:gender</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Implement model</strong></p>
<p>Fitting the model to entire dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>fit_acc1 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_clean2, <span class="at">std.lv =</span> T)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_acc1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 6 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        16

  Number of observations                           224

Model Test User Model:
                                                      
  Test statistic                               185.975
  Degrees of freedom                                 5
  P-value (Chi-square)                           0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.306    0.087    3.524    0.000
    SI_avg           -0.203    0.062   -3.244    0.001
    gender           -0.212    0.121   -1.746    0.081
    TMA_avg:gender    0.059    0.120    0.494    0.621
  Del_OverallAcc ~                                    
    TMA_avg          -0.071    0.097   -0.738    0.460
    MW_avg           -0.207    0.072   -2.856    0.004
    SI_avg           -0.007    0.069   -0.101    0.920
    gender           -0.085    0.132   -0.640    0.522
    MW_avg:gender     0.077    0.094    0.824    0.410
    TMA_avg:gender   -0.088    0.130   -0.676    0.499

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.121    0.092    1.314    0.189
   .Del_OverallAcc    0.053    0.100    0.533    0.594
    MW_avg:gender    -0.038    0.046   -0.821    0.412

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.799    0.075   10.583    0.000
   .Del_OverallAcc    0.937    0.088   10.583    0.000
    MW_avg:gender     0.475    0.045   10.583    0.000</code></pre>
</div>
</div>
<p>Multigroup analysis with condition:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>fit_acc2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_clean2, <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Condition"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_acc2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 12 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        32

  Number of observations per group:                   
    1                                              115
    0                                              109

Model Test User Model:
                                                      
  Test statistic                               189.042
  Degrees of freedom                                10
  P-value (Chi-square)                           0.000
  Test statistic for each group:
    1                                           80.529
    0                                          108.514

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.299    0.098    3.053    0.002
    SI_avg           -0.057    0.075   -0.760    0.447
    gender           -0.243    0.145   -1.676    0.094
    TMA_avg:gender   -0.212    0.151   -1.404    0.160
  Del_OverallAcc ~                                    
    TMA_avg           0.080    0.125    0.644    0.520
    MW_avg           -0.180    0.114   -1.569    0.117
    SI_avg            0.009    0.092    0.097    0.922
    gender           -0.033    0.180   -0.181    0.857
    MW_avg:gender     0.144    0.162    0.888    0.374
    TMA_avg:gender   -0.098    0.187   -0.523    0.601

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.007    0.109    0.064    0.949
   .Del_OverallAcc    0.046    0.136    0.338    0.735
    MW_avg:gender    -0.130    0.050   -2.618    0.009

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.573    0.076    7.583    0.000
   .Del_OverallAcc    0.862    0.114    7.583    0.000
    MW_avg:gender     0.284    0.037    7.583    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.293    0.144    2.038    0.042
    SI_avg           -0.291    0.103   -2.829    0.005
    gender           -0.136    0.189   -0.716    0.474
    TMA_avg:gender    0.197    0.180    1.096    0.273
  Del_OverallAcc ~                                    
    TMA_avg          -0.289    0.149   -1.940    0.052
    MW_avg           -0.225    0.097   -2.309    0.021
    SI_avg           -0.080    0.108   -0.739    0.460
    gender           -0.117    0.193   -0.605    0.545
    MW_avg:gender     0.100    0.116    0.864    0.388
    TMA_avg:gender    0.001    0.184    0.006    0.995

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.178    0.147    1.212    0.225
   .Del_OverallAcc    0.070    0.150    0.462    0.644
    MW_avg:gender     0.060    0.078    0.769    0.442

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.932    0.126    7.382    0.000
   .Del_OverallAcc    0.962    0.130    7.382    0.000
    MW_avg:gender     0.657    0.089    7.382    0.000</code></pre>
</div>
</div>
<p><strong>WE group:</strong></p>
<ul>
<li>Math anxiety had a significant positive effect on mind wandering</li>
</ul>
<p><strong>No WE group:</strong></p>
<ul>
<li><p>Math anxiety had a significant positive effect on mind wandering</p></li>
<li><p>Situational interest had a negative effect on mind wandering</p></li>
<li><p>Mind wandering had a significant negative effect on accuracy scores</p></li>
</ul>
<p>Looking closely at the differences in groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>fit_acc2.constrained <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, df_clean2, <span class="at">group =</span> <span class="st">"Condition"</span>, <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_acc2, fit_acc2.constrained)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

                     Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff
fit_acc2             10 1687.5 1796.7 189.04                           
fit_acc2.constrained 23 1687.7 1752.5 215.22     26.179 0.09514      13
                     Pr(&gt;Chisq)  
fit_acc2                         
fit_acc2.constrained    0.01608 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Some paths in the model are different among groups -&gt; Looking closely at the differences in the effect of math anxiety on mind wandering between groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># redefine model</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>m_acc.constrained <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + c("b1", "b1") * TMA_avg + SI_avg + gender +  TMA_avg:gender</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="st">Del_OverallAcc ~ 1 + TMA_avg + MW_avg + SI_avg + gender + MW_avg:gender +  TMA_avg:gender</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>fit_acc2.constrained2 <span class="ot">&lt;-</span> </span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sem</span>(m_acc.constrained, df_clean2, <span class="at">group =</span> <span class="st">"Condition"</span>)</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_acc2, fit_acc2.constrained2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

                      Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff
fit_acc2              10 1687.5 1796.7 189.04                         
fit_acc2.constrained2 11 1685.5 1791.3 189.04  0.0011131     0       1
                      Pr(&gt;Chisq)
fit_acc2                        
fit_acc2.constrained2     0.9734</code></pre>
</div>
</div>
<p>No significant difference between worked ex groups vs no worked ex groups on the effect of math anxiety on mind wandering.</p>
</section>
<section id="perceived-understanding" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="perceived-understanding"><span class="header-section-number">1.4.2</span> Perceived Understanding</h3>
<p><strong>Model definition</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>m_und <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + TMA_avg + SI_avg + gender + TMA_avg:gender</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="st">understand_avg ~ 1 + TMA_avg + MW_avg + SI_avg + gender + MW_avg:gender + TMA_avg:gender</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Implement model</strong></p>
<p>Fitting the model to entire dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>fit_und1 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_clean2, <span class="at">std.lv =</span> T)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_und1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 6 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        16

  Number of observations                           224

Model Test User Model:
                                                      
  Test statistic                               185.975
  Degrees of freedom                                 5
  P-value (Chi-square)                           0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.306    0.087    3.524    0.000
    SI_avg           -0.203    0.062   -3.244    0.001
    gender           -0.212    0.121   -1.746    0.081
    TMA_avg:gender    0.059    0.120    0.494    0.621
  understand_avg ~                                    
    TMA_avg           0.015    0.087    0.168    0.866
    MW_avg           -0.439    0.065   -6.705    0.000
    SI_avg            0.212    0.063    3.379    0.001
    gender            0.054    0.120    0.451    0.652
    MW_avg:gender     0.186    0.085    2.189    0.029
    TMA_avg:gender   -0.094    0.117   -0.800    0.424

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.121    0.092    1.314    0.189
   .understand_avg   -0.022    0.090   -0.246    0.805
    MW_avg:gender    -0.038    0.046   -0.821    0.412

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.799    0.075   10.583    0.000
   .understand_avg    0.766    0.072   10.583    0.000
    MW_avg:gender     0.475    0.045   10.583    0.000</code></pre>
</div>
</div>
<p>Multigroup analysis with condition:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>fit_und2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_clean2, <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Condition"</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_und2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 12 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        32

  Number of observations per group:                   
    1                                              115
    0                                              109

Model Test User Model:
                                                      
  Test statistic                               189.042
  Degrees of freedom                                10
  P-value (Chi-square)                           0.000
  Test statistic for each group:
    1                                           80.529
    0                                          108.514

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.299    0.098    3.053    0.002
    SI_avg           -0.057    0.075   -0.760    0.447
    gender           -0.243    0.145   -1.676    0.094
    TMA_avg:gender   -0.212    0.151   -1.404    0.160
  understand_avg ~                                    
    TMA_avg           0.067    0.110    0.612    0.540
    MW_avg           -0.537    0.101   -5.322    0.000
    SI_avg            0.288    0.081    3.560    0.000
    gender            0.275    0.159    1.729    0.084
    MW_avg:gender     0.436    0.143    3.044    0.002
    TMA_avg:gender   -0.188    0.165   -1.141    0.254

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.007    0.109    0.064    0.949
   .understand_avg   -0.127    0.120   -1.059    0.290
    MW_avg:gender    -0.130    0.050   -2.618    0.009

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.573    0.076    7.583    0.000
   .understand_avg    0.670    0.088    7.583    0.000
    MW_avg:gender     0.284    0.037    7.583    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.293    0.144    2.038    0.042
    SI_avg           -0.291    0.103   -2.829    0.005
    gender           -0.136    0.189   -0.716    0.474
    TMA_avg:gender    0.197    0.180    1.096    0.273
  understand_avg ~                                    
    TMA_avg          -0.044    0.139   -0.320    0.749
    MW_avg           -0.412    0.091   -4.547    0.000
    SI_avg            0.157    0.101    1.562    0.118
    gender           -0.098    0.180   -0.544    0.586
    MW_avg:gender     0.071    0.108    0.662    0.508
    TMA_avg:gender    0.019    0.171    0.111    0.912

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.178    0.147    1.212    0.225
   .understand_avg    0.054    0.140    0.387    0.698
    MW_avg:gender     0.060    0.078    0.769    0.442

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.932    0.126    7.382    0.000
   .understand_avg    0.834    0.113    7.382    0.000
    MW_avg:gender     0.657    0.089    7.382    0.000</code></pre>
</div>
</div>
<p><strong>WE group:</strong></p>
<ul>
<li><p>Math anxiety had significant positive effect on mind wandering</p></li>
<li><p>Mind wandering had a significant negative effect on perceived understanding</p></li>
<li><p>Situational interest had a significant positive effect on perceived understanding</p></li>
<li><p>Interaction effect between mind wandering and gender was significant</p>
<ul>
<li><p>Boys: <span class="math inline">\beta_{mw} = -0.537</span></p></li>
<li><p>Girls: <span class="math inline">\beta_{mw} = -0.101</span></p></li>
</ul>
<p>-&gt; Mind wandering impacted boys more than girls on their perceived understanding (girls pay attention more?)</p></li>
</ul>
<p><strong>No WE group:</strong></p>
<ul>
<li><p>Math anxiety had a significant positive effect on mind wandering</p></li>
<li><p>Situational interest had a significant negative effect on mind wandering</p></li>
<li><p>Mind wandering had a significant negative effect on perceived understanding</p></li>
</ul>
<p>Finding model difference between groups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>fit_und2.constrained <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, df_clean2, <span class="at">group =</span> <span class="st">"Condition"</span>, </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_und2, fit_und2.constrained)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

                     Df    AIC    BIC  Chisq Chisq diff    RMSEA Df diff
fit_und2             10 1643.1 1752.2 189.04                            
fit_und2.constrained 23 1641.8 1706.7 213.81     24.764 0.089888      13
                     Pr(&gt;Chisq)  
fit_und2                         
fit_und2.constrained    0.02478 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Some paths in the model may vary among groups -&gt; Looking at the effect of mind wandering on perceived understanding</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># redefine model</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>m_und.constrained <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + TMA_avg + SI_avg + gender +  TMA_avg:gender</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="st">understand_avg ~ 1 + TMA_avg + c("b1", "b1") * MW_avg + SI_avg + gender + MW_avg:gender +  TMA_avg:gender</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>fit_und2.constrained2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und.constrained, df_clean2, <span class="at">group =</span> <span class="st">"Condition"</span>)</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_und2, fit_und2.constrained2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

                      Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff
fit_und2              10 1643.1 1752.2 189.04                         
fit_und2.constrained2 11 1641.5 1747.3 189.52    0.47947     0       1
                      Pr(&gt;Chisq)
fit_und2                        
fit_und2.constrained2     0.4887</code></pre>
</div>
</div>
<p>No significant difference was observed on the effect of mind wandering on perceived understanding.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>