---
title: "Path Analysis w/ Moderation Effect"
format: html
editor: visual
---

# Path Analysis w/ Moderation Effect

## Load Libraries

```{r}
library(tidyverse)
library(lavaan)
library(semPlot)
```

## Load Data

```{r}
df <- read_csv("../../../data/df_imputed.csv")
head(df)
```

### Data Clearning

We need to add average for situational interest and mind wandering

```{r}
# average for situational interest and mind wandering
df <- df %>% mutate(SI_avg = rowMeans(df[12:25], na.rm=TRUE),
              MW_avg = rowMeans(df[26:32], na.rm=TRUE))
head(df[41:42])
```

```{r}
# Standardize data
df2 <- df %>% select(Sex, Condition, chicago,
                           TMA_avg, SI_avg, MW_avg, Del_OverallAcc, Understand_avg)
df2[4:8] <- df2[4:8] %>% mutate_all(~(scale(.) %>% as.vector))
```

```{r}
# subgroup data
df_we <-  df2 %>% filter(Condition == 1)
# chicago
df_we_c <-  df_we %>% filter(chicago == 1)
df_we_i <-  df_we %>% filter(chicago == 0)
# irvine
df_nwe <-  df2 %>% filter(Condition == 0)
# chicago
df_nwe_c <-  df_nwe %>% filter(chicago == 1)
# irvine
df_nwe_i <-  df_nwe %>% filter(chicago == 0)
```
