<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emi Cervantes">
<meta name="dcterms.date" content="2023-09-13">

<title>Modeling 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="modeling5_files/libs/clipboard/clipboard.min.js"></script>
<script src="modeling5_files/libs/quarto-html/quarto.js"></script>
<script src="modeling5_files/libs/quarto-html/popper.min.js"></script>
<script src="modeling5_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="modeling5_files/libs/quarto-html/anchor.min.js"></script>
<link href="modeling5_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="modeling5_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="modeling5_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="modeling5_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="modeling5_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link active" data-scroll-target="#load-libraries"><span class="header-section-number">1</span> Load Libraries</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data"><span class="header-section-number">2</span> Load Data</a>
  <ul class="collapse">
  <li><a href="#data-clearning" id="toc-data-clearning" class="nav-link" data-scroll-target="#data-clearning"><span class="header-section-number">2.1</span> Data Clearning</a></li>
  </ul></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">3</span> Model</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">3.1</span> Hypotheses</a></li>
  <li><a href="#overall-accuracy-scores" id="toc-overall-accuracy-scores" class="nav-link" data-scroll-target="#overall-accuracy-scores"><span class="header-section-number">3.2</span> Overall Accuracy Scores</a></li>
  <li><a href="#perceived-understanding" id="toc-perceived-understanding" class="nav-link" data-scroll-target="#perceived-understanding"><span class="header-section-number">3.3</span> Perceived Understanding</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="modeling5.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="modeling5.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modeling 5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emi Cervantes </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 13, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><strong>Modeling Procedures</strong></p>
<ol type="1">
<li>Fulfill the requirements to perform a path analysis: assumptions regarding sample size, multivariate normal distribution, and multicollinearity</li>
</ol>
<section id="load-libraries" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="load-libraries"><span class="header-section-number">1</span> Load Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-16
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="load-data"><span class="header-section-number">2</span> Load Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../../data/df_imputed.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 229 Columns: 40
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," dbl
(40): ...1, Condition, Sex, chicago, TMA_1, TMA_2, TMA_3, TMA_4, TMA_5, ...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 40
   ...1 Condition   Sex chicago TMA_1 TMA_2 TMA_3 TMA_4 TMA_5 TMA_6 TMA_avg
  &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     1         1     0       1     2     1     3     2     2     1    1.83
2     2         1     0       1     1     2     3     1     2     3    2   
3     3         1     0       1     1     1     1     2     3     5    2.17
4     4         1     1       1     2     2     1     1     2     2    1.67
5     5         0     1       1     2     1     1     3     2     3    2   
6     6         1     1       1     2     3     1     1     2     1    1.67
# ℹ 29 more variables: SI_1 &lt;dbl&gt;, SI_2 &lt;dbl&gt;, SI_3 &lt;dbl&gt;, SI_4 &lt;dbl&gt;,
#   SI_5 &lt;dbl&gt;, SI_6 &lt;dbl&gt;, SI_7 &lt;dbl&gt;, SI_8 &lt;dbl&gt;, SI_9 &lt;dbl&gt;, SI_10 &lt;dbl&gt;,
#   SI_11 &lt;dbl&gt;, SI_12 &lt;dbl&gt;, SI_13 &lt;dbl&gt;, SI_14 &lt;dbl&gt;, MW1_1 &lt;dbl&gt;,
#   MW1_2 &lt;dbl&gt;, MW1_3 &lt;dbl&gt;, MW1_4 &lt;dbl&gt;, MW1_5 &lt;dbl&gt;, MW1_6 &lt;dbl&gt;,
#   MW1_7 &lt;dbl&gt;, MW2_1 &lt;dbl&gt;, MW2_2 &lt;dbl&gt;, MW2_3 &lt;dbl&gt;, MW2_4 &lt;dbl&gt;,
#   MW2_5 &lt;dbl&gt;, Del_OverallAcc &lt;dbl&gt;, Understand_avg &lt;dbl&gt;, TMA &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="data-clearning" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-clearning"><span class="header-section-number">2.1</span> Data Clearning</h3>
<p>We need to add average for situational interest and mind wandering</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># average for situational interest and mind wandering</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">SI_avg =</span> <span class="fu">rowMeans</span>(df[<span class="dv">12</span><span class="sc">:</span><span class="dv">25</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">MW_avg =</span> <span class="fu">rowMeans</span>(df[<span class="dv">26</span><span class="sc">:</span><span class="dv">32</span>], <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df[<span class="dv">41</span><span class="sc">:</span><span class="dv">42</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  SI_avg MW_avg
   &lt;dbl&gt;  &lt;dbl&gt;
1   4.5    3   
2   2.93   2.86
3   3.14   3.43
4   4.36   3.14
5   4.79   3   
6   4.5    2.57</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(Sex, Condition, chicago,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                           TMA_avg, SI_avg, MW_avg, Del_OverallAcc, Understand_avg)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>df2[<span class="dv">4</span><span class="sc">:</span><span class="dv">8</span>] <span class="ot">&lt;-</span> df2[<span class="dv">4</span><span class="sc">:</span><span class="dv">8</span>] <span class="sc">%&gt;%</span> <span class="fu">mutate_all</span>(<span class="sc">~</span>(<span class="fu">scale</span>(.) <span class="sc">%&gt;%</span> as.vector))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subgroup data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df_we <span class="ot">&lt;-</span>  df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># chicago</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>df_we_c <span class="ot">&lt;-</span>  df_we <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>df_we_i <span class="ot">&lt;-</span>  df_we <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># irvine</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>df_nwe <span class="ot">&lt;-</span>  df2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># chicago</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>df_nwe_c <span class="ot">&lt;-</span>  df_nwe <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># irvine</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>df_nwe_i <span class="ot">&lt;-</span>  df_nwe <span class="sc">%&gt;%</span> <span class="fu">filter</span>(chicago <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="model" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="model"><span class="header-section-number">3</span> Model</h2>
<section id="hypotheses" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">3.1</span> Hypotheses</h3>
<p><span class="math inline">H1</span>: Trait math anxiety will have a direct positive effect on mind wandering and will have a direct negative effect on learning achievement</p>
<p><span class="math inline">H2</span>: Situational interest will have a direct positive effect on mind wandering, and will have a direct positive effect on learning achievement</p>
<p><span class="math inline">H3</span>: Mind wandering has a direct negative effect on learning achievement</p>
<p><span class="math inline">H4</span>: Trait math anxiety will have an indirect negative effect on learning achievement</p>
<p><span class="math inline">H5</span>: Situational interest will have an indirect positive effect on learning achievement</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># covariance table</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df2[<span class="dv">4</span><span class="sc">:</span><span class="dv">8</span>] <span class="sc">%&gt;%</span> <span class="fu">cov</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  TMA_avg       SI_avg       MW_avg Del_OverallAcc
TMA_avg         0.9676199 -0.215123598  0.311037273   -0.123845796
SI_avg         -0.2151236  0.977615176 -0.002155139    0.007010654
MW_avg          0.3110373 -0.002155139  1.000000000   -0.087502599
Del_OverallAcc -0.1238458  0.007010654 -0.087502599    0.984081085
Understand_avg -0.2075964  0.253191576 -0.200148397    0.237749605
               Understand_avg
TMA_avg            -0.2075964
SI_avg              0.2531916
MW_avg             -0.2001484
Del_OverallAcc      0.2377496
Understand_avg      0.9825640</code></pre>
</div>
</div>
</section>
<section id="overall-accuracy-scores" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="overall-accuracy-scores"><span class="header-section-number">3.2</span> Overall Accuracy Scores</h3>
<section id="model-definition" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="model-definition"><span class="header-section-number">3.2.1</span> Model Definition</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model definition</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>m_acc <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + TMA_avg + SI_avg</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="st">Del_OverallAcc ~ 1 + TMA_avg + MW_avg + SI_avg</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="worked-ex-group" class="level4" data-number="3.2.2">
<h4 data-number="3.2.2" class="anchored" data-anchor-id="worked-ex-group"><span class="header-section-number">3.2.2</span> Worked EX Group</h4>
<section id="full-sample" class="level5" data-number="3.2.2.1">
<h5 data-number="3.2.2.1" class="anchored" data-anchor-id="full-sample"><span class="header-section-number">3.2.2.1</span> Full Sample</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit1_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>fit2_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>fit3_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    0                                               54
    1                                               64

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.597    0.141    4.242    0.000
    SI_avg            0.268    0.163    1.640    0.101
  Del_OverallAcc ~                                    
    TMA_avg           0.172    0.153    1.129    0.259
    MW_avg           -0.099    0.128   -0.772    0.440
    SI_avg            0.086    0.157    0.544    0.586

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.019    0.162   -0.119    0.905
   .Del_OverallAcc    0.042    0.152    0.278    0.781

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            1.258    0.242    5.196    0.000
   .Del_OverallAcc    1.108    0.213    5.196    0.000


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.033    0.122    0.268    0.789
    SI_avg            0.116    0.106    1.096    0.273
  Del_OverallAcc ~                                    
    TMA_avg          -0.080    0.124   -0.642    0.521
    MW_avg           -0.145    0.128   -1.135    0.256
    SI_avg           -0.102    0.109   -0.934    0.350

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.121    0.099   -1.223    0.221
   .Del_OverallAcc   -0.004    0.102   -0.043    0.966

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.624    0.110    5.657    0.000
   .Del_OverallAcc    0.650    0.115    5.657    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we, fit2_we, fit3_we)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

        Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit1_we  0 665.96 715.83  0.0000                                        
fit2_we  2 662.31 706.64  0.3521     0.3521 0.00000       2    0.83857  
fit3_we  7 664.25 694.73 12.2951    11.9430 0.15341       5    0.03558 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Trait math anxiety had a positive direct effect on mind wandering for girls (<span class="math inline">\beta = 0.597, p &lt; 0.0001</span>). Boys did not have any direct effect on mind wandering by any predictors.</p>
<p>None of the predictors had any significant effects on students’ overall accuracy scores for boys and girls.</p>
</section>
<section id="chicago" class="level5" data-number="3.2.2.2">
<h5 data-number="3.2.2.2" class="anchored" data-anchor-id="chicago"><span class="header-section-number">3.2.2.2</span> Chicago</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fit1_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_c, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>fit2_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>fit3_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    0                                               17
    1                                                9

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.854    0.266    3.211    0.001
    SI_avg            0.247    0.449    0.551    0.582
  Del_OverallAcc ~                                    
    TMA_avg           0.044    0.207    0.212    0.832
    MW_avg           -0.101    0.149   -0.678    0.498
    SI_avg           -0.164    0.278   -0.590    0.555

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.292    0.511    0.572    0.567
   .Del_OverallAcc   -0.562    0.317   -1.777    0.076

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            2.043    0.701    2.915    0.004
   .Del_OverallAcc    0.770    0.264    2.915    0.004


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.853    0.686    1.244    0.213
    SI_avg            1.394    0.715    1.949    0.051
  Del_OverallAcc ~                                    
    TMA_avg          -2.090    0.627   -3.333    0.001
    MW_avg            0.317    0.282    1.127    0.260
    SI_avg           -2.226    0.720   -3.090    0.002

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.759    0.440   -1.726    0.084
   .Del_OverallAcc    0.532    0.428    1.241    0.215

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.451    0.212    2.121    0.034
   .Del_OverallAcc    0.321    0.152    2.121    0.034</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we_c, fit2_we_c, fit3_we_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

          Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit1_we_c  0 173.89 196.54  0.0000                                        
fit2_we_c  2 175.99 196.12  6.0989     6.0989 0.39705       2    0.04739 *
fit3_we_c  7 171.32 185.16 11.4285     5.3296 0.07121       5    0.37699  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we_c,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Trait math anxiety had a positive direct effect on mind wandering (<span class="math inline">\beta = 0.847, p &lt; 0.001</span>) for girls. On the other hand, for boys, neither trait math anxiety or situational interests had any direct effects on mind wandering.</p>
<p>None of the predictors had any significant effects on girls’ overall accuracy scores. For boys, trait math anxiety had negative direct effect on accuracy scores (<span class="math inline">\beta = -2.090, p = 0.001</span>) and situational interest also had negative direct effects on accuracy scores. (<span class="math inline">\beta = -2.226, p = 0.002</span>)</p>
</section>
<section id="irvine" class="level5" data-number="3.2.2.3">
<h5 data-number="3.2.2.3" class="anchored" data-anchor-id="irvine"><span class="header-section-number">3.2.2.3</span> Irvine</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fit1_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_i, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fit2_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>fit3_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_we_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    1                                               55
    0                                               37

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.099    0.131    0.755    0.450
    SI_avg            0.029    0.120    0.243    0.808
  Del_OverallAcc ~                                    
    TMA_avg          -0.082    0.130   -0.629    0.530
    MW_avg           -0.141    0.133   -1.064    0.287
    SI_avg           -0.012    0.118   -0.106    0.916

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.156    0.108   -1.447    0.148
   .Del_OverallAcc    0.093    0.108    0.857    0.391

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.608    0.116    5.244    0.000
   .Del_OverallAcc    0.590    0.113    5.244    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.338    0.146    2.314    0.021
    SI_avg            0.134    0.154    0.865    0.387
  Del_OverallAcc ~                                    
    TMA_avg           0.260    0.134    1.946    0.052
    MW_avg            0.260    0.141    1.851    0.064
    SI_avg            0.477    0.133    3.577    0.000

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.175    0.141   -1.240    0.215
   .Del_OverallAcc    0.467    0.123    3.782    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.721    0.168    4.301    0.000
   .Del_OverallAcc    0.527    0.123    4.301    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we_i, fit2_we_i, fit3_we_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

          Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)   
fit1_we_i  0 466.04 511.43  0.0000                                         
fit2_we_i  2 467.10 507.45  5.0603     5.0603 0.18239       2   0.079645 . 
fit3_we_i  7 472.69 500.43 20.6494    15.5891 0.21457       5   0.008121 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we_c,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had no direct effects on mind wandering. For boys, trait math anxiety had positive direct effect (<span class="math inline">\beta = 0.338, p = 0.021</span>) on mind wandering.</p>
<p>Girls did not have any direct/indirect effects on accuracy scores. Boys had both positive effects by trait math anxiety (<span class="math inline">\beta = 0.260, p = 0.052</span>) and situational interest (<span class="math inline">\beta = 0.477, p = 0.0001</span>)</p>
</section>
</section>
<section id="no-wokred-ex-group" class="level4" data-number="3.2.3">
<h4 data-number="3.2.3" class="anchored" data-anchor-id="no-wokred-ex-group"><span class="header-section-number">3.2.3</span> No Wokred EX Group</h4>
<section id="full-sample-1" class="level5" data-number="3.2.3.1">
<h5 data-number="3.2.3.1" class="anchored" data-anchor-id="full-sample-1"><span class="header-section-number">3.2.3.1</span> Full Sample</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fit2_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>fit3_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:               Used       Total
    1                                               65          65
    0                                               45          46

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.375    0.103    3.631    0.000
    SI_avg           -0.004    0.105   -0.033    0.973
  Del_OverallAcc ~                                    
    TMA_avg          -0.332    0.152   -2.183    0.029
    MW_avg            0.146    0.167    0.876    0.381
    SI_avg            0.059    0.141    0.416    0.677

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.083    0.097    0.853    0.394
   .Del_OverallAcc   -0.061    0.131   -0.469    0.639

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.608    0.107    5.701    0.000
   .Del_OverallAcc    1.097    0.192    5.701    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.130    0.150    0.864    0.387
    SI_avg           -0.082    0.148   -0.554    0.579
  Del_OverallAcc ~                                    
    TMA_avg          -0.273    0.136   -2.009    0.044
    MW_avg           -0.184    0.134   -1.376    0.169
    SI_avg           -0.213    0.134   -1.595    0.111

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.002    0.147   -0.011    0.991
   .Del_OverallAcc    0.022    0.131    0.166    0.868

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.933    0.197    4.743    0.000
   .Del_OverallAcc    0.751    0.158    4.743    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe, fit2_nwe, fit3_nwe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)
fit1_nwe  0 618.05 666.66 0.0000                                       
fit2_nwe  2 614.49 657.69 0.4311     0.4311 0.000000       2     0.8061
fit3_nwe  7 610.49 640.19 6.4308     5.9997 0.060292       5     0.3063</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.375, p = 0.0001</span>). Boys did not have any direct effect on mind wandering.</p>
<p>Girls had negative direct effect on accuracy scores by trait math anxiety (<span class="math inline">\beta = -0.332, p = 0.029</span>). Boys had negative direct on accuracy scores by trait math anxiety (<span class="math inline">\beta = -0.273, p = 0.044</span>).</p>
<p>Girls had worst effect on trait math anxiety than boys.</p>
</section>
<section id="chicago-1" class="level5" data-number="3.2.3.2">
<h5 data-number="3.2.3.2" class="anchored" data-anchor-id="chicago-1"><span class="header-section-number">3.2.3.2</span> Chicago</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_c, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>fit2_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>fit3_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    1                                               14
    0                                               11

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.190    0.489    0.389    0.697
    SI_avg           -0.231    0.252   -0.916    0.360
  Del_OverallAcc ~                                    
    TMA_avg          -0.562    0.456   -1.232    0.218
    MW_avg            0.021    0.248    0.084    0.933
    SI_avg           -0.224    0.241   -0.929    0.353

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.013    0.263   -0.049    0.961
   .Del_OverallAcc   -1.264    0.245   -5.166    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.726    0.274    2.646    0.008
   .Del_OverallAcc    0.626    0.237    2.646    0.008


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.419    0.164    2.552    0.011
    SI_avg            0.487    0.209    2.325    0.020
  Del_OverallAcc ~                                    
    TMA_avg          -0.580    0.283   -2.049    0.040
    MW_avg            0.261    0.413    0.633    0.527
    SI_avg           -0.410    0.350   -1.171    0.241

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.198    0.158   -1.248    0.212
   .Del_OverallAcc   -0.345    0.231   -1.488    0.137

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.275    0.117    2.345    0.019
   .Del_OverallAcc    0.516    0.220    2.345    0.019</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe_c, fit2_nwe_c, fit3_nwe_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

           Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit1_nwe_c  0 145.38 167.32  0.0000                                        
fit2_nwe_c  2 148.26 167.76  6.8786     6.8786 0.44175       2    0.03209 *
fit3_nwe_c  7 142.90 156.30 11.5156     4.6370 0.00000       5    0.46177  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe_c,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls did not have any direct effects on mind wandering. Boys had direct positive effects on mind wandering by both trait math anxiety (<span class="math inline">\beta = 0.419, p = 0.011</span>) and situational interest (<span class="math inline">\beta = 0.487, p = 0.020</span>).</p>
<p>Girls did not have any direct effects on accuracy scores. Boys had significant negative direct effect on accuracy scores by trait math anxiety (<span class="math inline">\beta = -0.580, p = 0.040</span>).</p>
</section>
<section id="irvine-1" class="level5" data-number="3.2.3.3">
<h5 data-number="3.2.3.3" class="anchored" data-anchor-id="irvine-1"><span class="header-section-number">3.2.3.3</span> Irvine</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_i, </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>fit2_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>fit3_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_acc, <span class="at">data =</span> df_nwe_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:               Used       Total
    0                                               34          35
    1                                               51          51

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.096    0.192    0.502    0.616
    SI_avg           -0.166    0.174   -0.952    0.341
  Del_OverallAcc ~                                    
    TMA_avg          -0.189    0.157   -1.204    0.228
    MW_avg           -0.253    0.139   -1.815    0.070
    SI_avg           -0.205    0.144   -1.425    0.154

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.038    0.182    0.211    0.833
   .Del_OverallAcc    0.180    0.148    1.213    0.225

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            1.063    0.258    4.123    0.000
   .Del_OverallAcc    0.703    0.171    4.123    0.000


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.390    0.104    3.770    0.000
    SI_avg            0.062    0.114    0.543    0.587
  Del_OverallAcc ~                                    
    TMA_avg          -0.381    0.129   -2.945    0.003
    MW_avg            0.082    0.155    0.531    0.595
    SI_avg            0.204    0.126    1.622    0.105

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.115    0.106    1.079    0.281
   .Del_OverallAcc    0.304    0.119    2.562    0.010

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.558    0.110    5.050    0.000
   .Del_OverallAcc    0.680    0.135    5.050    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe_i, fit2_nwe_i, fit3_nwe_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

           Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit1_nwe_i  0 459.13 503.09  0.0000                                        
fit2_nwe_i  2 455.69 494.77  0.5629     0.5629 0.00000       2    0.75469  
fit3_nwe_i  7 455.50 482.37 10.3773     9.8144 0.15052       5    0.08067 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe_i,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Accuracy"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls did not have any direct effects on mind wandering. Boys had positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.390, p = 0.0001</span>).</p>
<p>Girls did not have any direct effects on accuracy scores. Boys had a negative direct effect on overall accuracy by trait math anxiety (<span class="math inline">\beta = -0.381, p = 0.003</span>).</p>
</section>
</section>
</section>
<section id="perceived-understanding" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="perceived-understanding"><span class="header-section-number">3.3</span> Perceived Understanding</h3>
<section id="model-definition-1" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="model-definition-1"><span class="header-section-number">3.3.1</span> Model Definition</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model definition</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>m_und <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="st"># regressions</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="st">MW_avg ~ 1 + TMA_avg + SI_avg</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">Understand_avg ~ 1 + TMA_avg + MW_avg + SI_avg</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="worked-ex-group-1" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="worked-ex-group-1"><span class="header-section-number">3.3.2</span> Worked EX Group</h4>
<section id="full-sample-2" class="level5" data-number="3.3.2.1">
<h5 data-number="3.3.2.1" class="anchored" data-anchor-id="full-sample-2"><span class="header-section-number">3.3.2.1</span> Full Sample</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fit1_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we, </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>fit2_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>fit3_we <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    0                                               54
    1                                               64

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.597    0.141    4.242    0.000
    SI_avg            0.268    0.163    1.640    0.101
  Understand_avg ~                                    
    TMA_avg          -0.043    0.142   -0.304    0.761
    MW_avg           -0.129    0.119   -1.083    0.279
    SI_avg            0.184    0.146    1.258    0.208

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.019    0.162   -0.119    0.905
   .Understand_avg   -0.064    0.141   -0.451    0.652

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            1.258    0.242    5.196    0.000
   .Understand_avg    0.961    0.185    5.196    0.000


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.033    0.122    0.268    0.789
    SI_avg            0.116    0.106    1.096    0.273
  Understand_avg ~                                    
    TMA_avg          -0.143    0.117   -1.222    0.222
    MW_avg           -0.137    0.120   -1.141    0.254
    SI_avg            0.351    0.103    3.415    0.001

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.121    0.099   -1.223    0.221
   .Understand_avg    0.146    0.096    1.521    0.128

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.624    0.110    5.657    0.000
   .Understand_avg    0.576    0.102    5.657    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we, fit2_we, fit3_we)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

        Df    AIC    BIC   Chisq Chisq diff  RMSEA Df diff Pr(&gt;Chisq)  
fit1_we  0 650.52 700.39  0.0000                                       
fit2_we  2 648.30 692.64  1.7849     1.7849 0.0000       2    0.40965  
fit3_we  7 649.39 679.86 12.8677    11.0828 0.1436       5    0.04976 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had a positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.597, p = 0.0001</span>). Boys did not have any significant direct effect on mind wandering.</p>
<p>Girls did not have any direct effects on perceived understanding. Boys had a positive direct effect on perceived understanding by situational interest (<span class="math inline">\beta = 0.351, p = 0.001</span>).</p>
</section>
<section id="chicago-2" class="level5" data-number="3.3.2.2">
<h5 data-number="3.3.2.2" class="anchored" data-anchor-id="chicago-2"><span class="header-section-number">3.3.2.2</span> Chicago</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fit1_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_c, </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>fit2_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>fit3_we_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    0                                               17
    1                                                9

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.854    0.266    3.211    0.001
    SI_avg            0.247    0.449    0.551    0.582
  Understand_avg ~                                    
    TMA_avg           0.213    0.279    0.763    0.446
    MW_avg           -0.206    0.201   -1.024    0.306
    SI_avg            0.086    0.375    0.230    0.818

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.292    0.511    0.572    0.567
   .Understand_avg   -0.399    0.427   -0.936    0.349

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            2.043    0.701    2.915    0.004
   .Understand_avg    1.401    0.480    2.915    0.004


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.853    0.686    1.244    0.213
    SI_avg            1.394    0.715    1.949    0.051
  Understand_avg ~                                    
    TMA_avg          -0.015    0.409   -0.036    0.971
    MW_avg           -0.345    0.183   -1.880    0.060
    SI_avg            1.246    0.469    2.656    0.008

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.759    0.440   -1.726    0.084
   .Understand_avg   -0.988    0.279   -3.539    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.451    0.212    2.121    0.034
   .Understand_avg    0.136    0.064    2.121    0.034</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we_c, fit2_we_c, fit3_we_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

          Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
fit1_we_c  0 176.34 198.99  0.000                                        
fit2_we_c  2 175.96 196.09  3.618      3.618 0.24946       2    0.16382  
fit3_we_c  7 175.30 189.14 12.959      9.341 0.25843       5    0.09621 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we_c,</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had a positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.854, p = 0.001</span>). Boys did not have any direct effect on mind wandering.</p>
<p>Girls did not have any direct effects on perceived understanding. Boys had a positive effect on perceived understanding by situational interest (<span class="math inline">\beta = 1.246, p = 0.008</span>).</p>
</section>
<section id="irvine-2" class="level5" data-number="3.3.2.3">
<h5 data-number="3.3.2.3" class="anchored" data-anchor-id="irvine-2"><span class="header-section-number">3.3.2.3</span> Irvine</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fit1_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_i, </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>fit2_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>fit3_we_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_we_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_we_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    1                                               55
    0                                               37

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.099    0.131    0.755    0.450
    SI_avg            0.029    0.120    0.243    0.808
  Understand_avg ~                                    
    TMA_avg          -0.095    0.126   -0.753    0.452
    MW_avg           -0.144    0.129   -1.118    0.263
    SI_avg            0.368    0.114    3.217    0.001

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.156    0.108   -1.447    0.148
   .Understand_avg    0.229    0.105    2.188    0.029

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.608    0.116    5.244    0.000
   .Understand_avg    0.556    0.106    5.244    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.338    0.146    2.314    0.021
    SI_avg            0.134    0.154    0.865    0.387
  Understand_avg ~                                    
    TMA_avg          -0.204    0.130   -1.573    0.116
    MW_avg            0.024    0.137    0.179    0.858
    SI_avg            0.387    0.130    2.986    0.003

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.175    0.141   -1.240    0.215
   .Understand_avg    0.139    0.120    1.160    0.246

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.721    0.168    4.301    0.000
   .Understand_avg    0.497    0.116    4.301    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_we_i, fit2_we_i, fit3_we_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

          Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
fit1_we_i  0 460.54 505.93 0.0000                                    
fit2_we_i  2 456.87 497.22 0.3327    0.33267     0       2     0.8468
fit3_we_i  7 449.83 477.57 3.2911    2.95845     0       5     0.7064</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_we_i,</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls did not have any direct effect on mind wandering. Boys had a positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.338, p = 0.021</span>).</p>
<p>Girls had a positive effect on perceived understanding by situational interest (<span class="math inline">\beta = 0.368, p = 0.001</span>). Boys had a positive effect on perceived understanding by situational interest (<span class="math inline">\beta = 0.387, p = 0.003</span>).</p>
<p>Effects on perceived understanding by situational interest were somewhat the same for both girls and boys.</p>
</section>
</section>
<section id="no-wokred-ex-group-1" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="no-wokred-ex-group-1"><span class="header-section-number">3.3.3</span> No Wokred EX Group</h4>
<section id="full-sample-3" class="level5" data-number="3.3.3.1">
<h5 data-number="3.3.3.1" class="anchored" data-anchor-id="full-sample-3"><span class="header-section-number">3.3.3.1</span> Full Sample</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>fit2_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>fit3_nwe <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:               Used       Total
    1                                               65          65
    0                                               45          46

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.375    0.103    3.631    0.000
    SI_avg           -0.004    0.105   -0.033    0.973
  Understand_avg ~                                    
    TMA_avg          -0.281    0.149   -1.885    0.059
    MW_avg           -0.066    0.163   -0.405    0.685
    SI_avg            0.145    0.138    1.051    0.293

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.083    0.097    0.853    0.394
   .Understand_avg   -0.060    0.129   -0.469    0.639

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.608    0.107    5.701    0.000
   .Understand_avg    1.055    0.185    5.701    0.000


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.130    0.150    0.864    0.387
    SI_avg           -0.082    0.148   -0.554    0.579
  Understand_avg ~                                    
    TMA_avg          -0.029    0.135   -0.217    0.828
    MW_avg           -0.342    0.132   -2.580    0.010
    SI_avg            0.242    0.132    1.829    0.067

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.002    0.147   -0.011    0.991
   .Understand_avg    0.026    0.130    0.201    0.840

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.933    0.197    4.743    0.000
   .Understand_avg    0.737    0.155    4.743    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe, fit2_nwe, fit3_nwe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

         Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
fit1_nwe  0 614.65 663.26 0.0000                                    
fit2_nwe  2 611.11 654.31 0.4537     0.4537     0       2     0.7970
fit3_nwe  7 605.34 635.04 4.6866     4.2329     0       5     0.5164</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had a positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.375, p = 0.0001</span>). Boys had no direct effect on mind wandering.</p>
<p>Girls did not have any direct effects on perceived understanding. Boys had a negative direct effect on perceived understanding by mind wandering (<span class="math inline">\beta = -0.342, p = 0.010</span>).</p>
</section>
<section id="chicago-3" class="level5" data-number="3.3.3.2">
<h5 data-number="3.3.3.2" class="anchored" data-anchor-id="chicago-3"><span class="header-section-number">3.3.3.2</span> Chicago</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_c, </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>fit2_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>fit3_nwe_c <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_c, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:                   
    1                                               14
    0                                               11

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    1                                            0.000
    0                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.190    0.489    0.389    0.697
    SI_avg           -0.231    0.252   -0.916    0.360
  Understand_avg ~                                    
    TMA_avg          -0.804    0.586   -1.372    0.170
    MW_avg            0.226    0.319    0.708    0.479
    SI_avg           -0.220    0.309   -0.711    0.477

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.013    0.263   -0.049    0.961
   .Understand_avg   -0.722    0.314   -2.300    0.021

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.726    0.274    2.646    0.008
   .Understand_avg    1.031    0.390    2.646    0.008


Group 2 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.419    0.164    2.552    0.011
    SI_avg            0.487    0.209    2.325    0.020
  Understand_avg ~                                    
    TMA_avg          -0.110    0.327   -0.336    0.737
    MW_avg           -0.249    0.476   -0.522    0.601
    SI_avg            0.281    0.404    0.696    0.487

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg           -0.198    0.158   -1.248    0.212
   .Understand_avg   -0.045    0.267   -0.170    0.865

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.275    0.117    2.345    0.019
   .Understand_avg    0.686    0.293    2.345    0.019</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe_c, fit2_nwe_c, fit3_nwe_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

           Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)
fit1_nwe_c  0 155.50 177.44 0.0000                                      
fit2_nwe_c  2 154.42 173.93 2.9198     2.9198 0.19182       2     0.2323
fit3_nwe_c  7 150.63 164.03 9.1236     6.2038 0.13878       5     0.2869</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe_c,</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls did not have any direct effect on mind wandering. Boys had positive effects on perceived understanding by both trait math anxiety (<span class="math inline">\beta = 0.419, p = 0.011</span>) and situational interest (<span class="math inline">\beta = 0.487, p = 0.020</span>).</p>
<p>Girls did not have any direct effect on perceived understanding. Boys had a negative direct effect on perceived understanding by trait math anxiety (<span class="math inline">\beta = -0.580, p = 0.040</span>).</p>
</section>
<section id="irvine-3" class="level5" data-number="3.3.3.3">
<h5 data-number="3.3.3.3" class="anchored" data-anchor-id="irvine-3"><span class="header-section-number">3.3.3.3</span> Irvine</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>fit1_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_i, </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.lv =</span> T, <span class="at">group =</span> <span class="st">"Sex"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>fit2_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="st">"intercepts"</span>)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>fit3_nwe_i <span class="ot">&lt;-</span> <span class="fu">sem</span>(m_und, <span class="at">data =</span> df_nwe_i, <span class="at">group =</span> <span class="st">"Sex"</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"intercepts"</span>, <span class="st">"regressions"</span>))</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_nwe_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.16 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        18

  Number of observations per group:               Used       Total
    0                                               34          35
    1                                               51          51

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0
  Test statistic for each group:
    0                                            0.000
    1                                            0.000

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [0]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.096    0.192    0.502    0.616
    SI_avg           -0.166    0.174   -0.952    0.341
  Understand_avg ~                                    
    TMA_avg           0.011    0.161    0.065    0.948
    MW_avg           -0.364    0.143   -2.540    0.011
    SI_avg            0.223    0.148    1.510    0.131

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.038    0.182    0.211    0.833
   .Understand_avg    0.054    0.152    0.355    0.723

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            1.063    0.258    4.123    0.000
   .Understand_avg    0.742    0.180    4.123    0.000


Group 2 [1]:

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  MW_avg ~                                            
    TMA_avg           0.390    0.104    3.770    0.000
    SI_avg            0.062    0.114    0.543    0.587
  Understand_avg ~                                    
    TMA_avg          -0.209    0.142   -1.475    0.140
    MW_avg           -0.263    0.170   -1.551    0.121
    SI_avg            0.308    0.138    2.231    0.026

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.115    0.106    1.079    0.281
   .Understand_avg    0.157    0.130    1.202    0.230

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .MW_avg            0.558    0.110    5.050    0.000
   .Understand_avg    0.819    0.162    5.050    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(fit1_nwe_i, fit2_nwe_i, fit3_nwe_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

           Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
fit1_nwe_i  0 470.40 514.36 0.0000                                    
fit2_nwe_i  2 466.79 505.87 0.3939     0.3939     0       2     0.8212
fit3_nwe_i  7 460.57 487.44 4.1713     3.7775     0       5     0.5819</code></pre>
</div>
</div>
<p>Visualizations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(fit1_nwe_i,</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">10</span>,</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.15</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">nCharEdges =</span> <span class="dv">0</span>,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nodeLabels =</span> <span class="fu">c</span>(<span class="st">"MW"</span>, <span class="st">"Understanding"</span>,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"TMA"</span>,<span class="st">"SI"</span>),</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="modeling5_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Results</strong></p>
<p>Girls had no direct effect on mind wandering. Boys had a positive direct effect on mind wandering by trait math anxiety (<span class="math inline">\beta = 0.390, p = 0.000</span>).</p>
<p>Girls had no direct/indirect effect on perceived understanding. Boys had a negative direct effect on perceived understanding by trait math anxiety (<span class="math inline">\beta = -0.381, p = 0.003</span>).</p>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>