---
title: "Math COVID eda 5"
author: "Emi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gridExtra)
library(ggpubr)
```

# Load Data

```{r}
dfr <- readxl::read_xlsx("../../data/math-anxiety-raw-data.xlsx")
clean <- read.csv("../../data/clean3.csv")
```

# Data Visualizations: tma

```{r}
dfr <-dfr %>% filter(Condition == 1 | Condition == 2)
dfr <- dfr %>% mutate(mw_avg = rowMeans(dfr[346:347], na.rm = TRUE))
dfr$Condition[dfr$Condition == 1] = 0 
dfr$Condition[dfr$Condition == 2] = 1 
df <- dfr %>% select(Del_OverallAcc, TMA_avg, Condition, mw_avg, SI_avg) %>% 
  drop_na()

dfr %>% filter(Condition == 0)
```

```{r}
tma1_hist <- dfr %>% 
  ggplot(aes(TMA_1, fill = Condition)) + geom_bar() +
  theme_minimal()  + 
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "TMA 1", y = "Count") +
  facet_grid(vars(cols = Condition))

tma2_hist <- dfr %>% 
  ggplot(aes(TMA_2,  fill = Condition)) + geom_bar()  +
  theme_minimal()  +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) + 
  labs(x = "TMA 2", y = "Count") +
  facet_grid(vars(cols = Condition))

tma3_hist <- dfr %>% 
  ggplot(aes(TMA_3,  fill = Condition)) + geom_bar()  +
  theme_minimal()  +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  facet_grid(vars(cols = Condition))

tma4_hist <- dfr %>% 
  ggplot(aes(TMA_4,  fill = Condition)) + geom_bar()   + theme_minimal() + 
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "TMA 4", y = "Count") +
  theme_minimal() + 
  facet_grid(vars(cols = Condition))

tma5_hist <- dfr %>% 
  ggplot(aes(TMA_5,  fill = Condition)) + geom_bar() +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "TMA 5", y = "Count") +
  theme_minimal() + 
  facet_grid(vars(cols = Condition))

tma6_hist <- dfr %>% 
  ggplot(aes(TMA_6,  fill = Condition)) + geom_bar()  +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "TMA 6", y = "Count") +
  theme_minimal() + 
  facet_grid(vars(cols = Condition))
```

```{r}
tma_hist <- ggarrange(tma1_hist, tma2_hist, tma3_hist, tma4_hist, tma5_hist, tma6_hist,common.legend = TRUE, legend="bottom", ncol = 3, nrow = 2)

ggsave(tma_hist, file = "../../outputs/visualization/tma_hist.png")
```

# Accuracy

```{r}
dfr %>% select(contains("acc"))

 tma_acc_splt1 <- df %>% 
  ggplot(aes(x = Del_OverallAcc, y = TMA_avg ,color  = Condition)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() + 
  scale_color_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  facet_grid(.~Condition) +
  labs(title = "Effect of Math Anxiety on Overall Accuracy",
        x = "Overall Accuracy", y = "TMA Average")

 tma_acc_splt2 <- df %>% 
              ggplot(aes(x = TMA_avg, y = Del_OverallAcc ,color  = Condition)) + 
              geom_point() +
              geom_smooth(method = "lm", se = FALSE) +
              theme_minimal() + 
              scale_color_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
              facet_grid(.~Condition)  +
              labs(title = "Effect of Math Anxiety on Overall Accuracy",
                    x = "TMA Average", y = "Overall Accuracy")
 
ggsave(plot = tma_acc_splt1, 
       file = "../../outputs/visualization/tma_acc_splt1.png")
ggsave(plot = tma_acc_splt2, 
       file = "../../outputs/visualization/tma_acc_splt2.png")
```

```{r}
t.test(Del_OverallAcc ~ Condition, data = dfr)
```

# Editing Visualizations

```{r}
# New facet label names for supp variable
cond.labs <- c("No Worked EX", "Worked EX")
names(cond.labs) <- c(0, 1)

# side by side plot with borders
tma_acc_splt3 <- df %>% 
            ggplot(aes(x = TMA_avg, y = Del_OverallAcc ,color  = Condition)) + 
            geom_point() +
            geom_smooth(method = "lm", se = FALSE) +
            theme_bw() + 
            scale_color_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
            facet_grid(.~Condition,
                       labeller = labeller(Condition = cond.labs))  +
            labs(title = "Effect of Trait Math Anxiety on Overall Accuracy",
                              x = "Average Trait Math Anxiety", y = "Overall Accuracy")  +
  theme(plot.title = element_text(face = "bold", hjust = 0.5))

tma_acc_splt3 <- tma_acc_splt3 + theme(legend.position = "none")
ggsave(plot = tma_acc_splt3, 
       file = "../../outputs/visualization/tma_acc_splt3.png", height = 5, width = 7)
```

```{r}
# TMA vs understanding with no facet grid
tma_acc1 <- dfr %>% 
  ggplot(aes(x = TMA_avg, y = Del_OverallAcc ,color  = Condition)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() + 
  scale_color_brewer(palette="Set1", labels = 
                                  c("Worked Ex", "No Worked EX")) +
  labs(title = "Effect of Math Anxiety on Overall Accuracy",
                    x = "TMA Average", y = "Overall Accuracy")

# No points, just smooth lines for each group
tma_acc2 <- dfr %>% 
  ggplot(aes(x = TMA_avg, y = Del_OverallAcc ,color  = Condition)) + 
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() + 
  scale_color_brewer(palette="Set1", labels = 
                                  c("Worked Ex", "No Worked EX")) +
  labs(title = "Effect of Math Anxiety on Overall Accuracy",
                    x = "TMA Average", y = "Overall Accuracy")
```

# More Visualizations

We want to visualize the mean of TMA for each TMA survey question

```{r}
tma_avg <- dfr %>% 
                  group_by(Condition) %>% 
                  summarize("TMA 1 Avg" = mean(TMA_1, na.rm = TRUE),
                            "TMA 2 Avg" = mean(TMA_2, na.rm = TRUE),
                            "TMA 3 Avg" = mean(TMA_3, na.rm = TRUE),
                            "TMA 4 Avg" = mean(TMA_4, na.rm = TRUE),
                            "TMA 5 Avg" = mean(TMA_5, na.rm = TRUE),
                            "TMA 6 Avg" = mean(TMA_6, na.rm = TRUE))
tma_avg
  
```

# More Visualizations: Relationship between MW/SI with Understanding

```{r}
dfr <- dfr %>% mutate(mw_avg = rowMeans(dfr[346:347], na.rm = TRUE))
# MW vs post-acc
mw_acc1 <- dfr %>% 
          ggplot(aes(x = mw_avg, y = Del_OverallAcc, color = Condition)) +
          geom_point() + geom_smooth(method = "lm", se = FALSE) +
          theme_bw() + 
          scale_color_brewer(palette="Set1", labels = 
                                          c("Worked Ex", "No Worked EX")) +
          labs(x = "Mind Wandering", y = "Overall Accuracy")
# MW vs post-acc (just smooth lines, no dots)
mw_acc2 <- dfr %>% 
          ggplot(aes(x = mw_avg, y = Del_OverallAcc, color = Condition)) +
          geom_smooth(method = "lm", se = FALSE) +
          theme_bw() + 
          scale_color_brewer(palette="Set1", labels = 
                                          c("Worked Ex", "No Worked EX")) +
          labs(x = "Mind Wandering", y = "Overall Accuracy")
#SI vs post-acc
si_acc1 <- dfr %>% 
  ggplot(aes(x = SI_avg, y = Del_OverallAcc, color = Condition)) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  theme_bw() + 
  scale_color_brewer(palette="Set1", labels = 
                                  c("Worked Ex", "No Worked EX")) +
  labs(x = "Situational Interest", y = "Overall Accuracy")
# SI vs post-acc (just smooth lines)
si_acc2 <- dfr %>% 
  ggplot(aes(x = SI_avg, y = Del_OverallAcc, color = Condition)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() + 
  scale_color_brewer(palette="Set1", labels = 
                                  c("Worked Ex", "No Worked EX")) +
  labs(x = "Situational Interest", y = "Overall Accuracy")
```

```{r}
# Side-by-side plot mw and situational interests with understanding
mw_si_plot1 <- ggarrange(mw_acc1, si_acc1,
                       common.legend = TRUE, legend="bottom", ncol = 2, nrow = 1)
mw_si_plot2 <- ggarrange(mw_acc2, si_acc2,
                       common.legend = TRUE, legend="bottom", ncol = 2, nrow = 1)
```

```{r}
mw_si_plot1
mw_si_plot2
```

```{r}
acc_avg_plt <- df %>% 
  group_by(Condition) %>% 
  summarize(acc_avg = mean(Del_OverallAcc), acc_sd = sd(Del_OverallAcc)) %>% 
  ggplot(aes(x = Condition, y = acc_avg, fill = Condition)) +
  geom_bar(position="dodge", stat="identity", color = "black") + 
  geom_errorbar(aes(ymin = acc_avg - acc_sd, ymax = acc_avg + acc_sd), width = 0.5) +
  theme_bw() + 
  scale_x_discrete(breaks=c(0,1),
        labels=c("No Worked EX","Worked EX")) +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "Condition", y = "Overall Accuracy", title = "Average Overall Accuracy Scores") + theme(legend.position = "none", plot.title = element_text(face = "bold", hjust = 0.5)) + ylim(0,1) 

tma_avg_plt <- df %>% 
  group_by(Condition) %>% 
  summarize(tma_avg = mean(TMA_avg), tma_sd = sd(TMA_avg))  %>% 
  ggplot(aes(x = Condition, y = tma_avg, fill = Condition)) +
  geom_bar(position="dodge", stat="identity", color = "black") + 
  geom_errorbar(aes(ymin = tma_avg - tma_sd, ymax = tma_avg + tma_sd), width = 0.5) + 
  theme_bw() + 
  scale_x_discrete(breaks=c(0,1),
        labels=c("No Worked EX","Worked EX")) +
  scale_fill_manual(values = c("#ef476f","#1b9aaa"), labels = 
                                  c("No Worked EX", "Worked EX")) +
  labs(x = "Condition", y = "Trait Math Anxiety", title = "Average Trait Math Anxiety Scores")+ theme(legend.position = "none") + ylim(0,5) +
  theme(plot.title = element_text(face = "bold", hjust = 0.5))
```


```{r}
avg_bar <- ggarrange(acc_avg_plt, tma_avg_plt, ncol = 2, nrow = 1)
ggsave(avg_bar, file = "../../outputs/visualization/avg_bar.png", height = 5, width = 7)
```

```{r}
summary(df$Del_OverallAcc)
```

```{r}
df %>% filter(Condition == 0)
```

# Find the average of students' math anxiety

```{r}
df %>% 
  group_by(Condition) %>% 
  summarize(tma_avg = mean(TMA_avg)) 

df %>% 
  group_by(Condition) %>% 
  summarize(tma_avg = mean(Del_OverallAcc)) 
```

```{r}
n_high_tma <- df %>% filter(TMA_avg >= 3) %>% nrow()
n_high_tma / nrow(df)
```



